// Accepted S4.5 schema snapshot. Runtime schema is validated by the migration manifest.
import { sql } from "drizzle-orm";
import { sqliteTable, sqliteTableCreator, text, integer, real, blob, uniqueIndex, index, check, foreignKey } from "drizzle-orm/sqlite-core";

const sqliteTableCustom = sqliteTableCreator((name) => name);

export const absence_reason_class_entries = sqliteTable("absence_reason_class_entries", {
    "id": integer().primaryKey(),
    "class_name": text().notNull(),
    "month": integer().notNull(),
    "year": integer().notNull(),
    "sakit": integer().notNull(),
    "izin": integer().notNull(),
    "alfa": integer().notNull(),
    "note": text(),
    "entered_by": text().notNull(),
    "entered_at": text().notNull(),
    "updated_at": text().notNull(),
});
export const absence_reasons = sqliteTable("absence_reasons", {
    "id": integer().primaryKey(),
    "student_id": integer().notNull(),
    "class_name": text().notNull(),
    "month": integer().notNull(),
    "year": integer().notNull(),
    "sakit": integer().notNull(),
    "izin": integer().notNull(),
    "alfa": integer().notNull(),
    "note": text(),
    "entered_by": text().notNull(),
    "entered_at": text().notNull(),
    "updated_at": text().notNull(),
});
export const academic_classes = sqliteTable("academic_classes", {
    "id": integer().primaryKey(),
    "academic_year_id": integer().notNull(),
    "grade_id": integer().notNull(),
    "class_name": text().notNull(),
    "section_code": text().notNull().default(""),
    "active": integer().notNull().default(1),
    "dapodik_rombongan_belajar_id": text(),
    "dapodik_sekolah_id": text(),
    "dapodik_semester_id": text(),
    "dapodik_last_update_at": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const academic_grades = sqliteTable("academic_grades", {
    "id": integer().primaryKey(),
    "jenjang_id": integer().notNull(),
    "program_id": integer().notNull(),
    "name": text().notNull(),
    "sequence_number": integer().notNull(),
    "active": integer().notNull().default(1),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const academic_interventions = sqliteTable("academic_interventions", {
    "id": integer().primaryKey(),
    "student_id": integer().notNull(),
    "enrollment_id": integer(),
    "academic_year_id": integer().notNull(),
    "jenjang_id": integer(),
    "subject_id": integer().notNull(),
    "assessment_type": text(),
    "term": text(),
    "class_name": text(),
    "student_name": text().notNull(),
    "subject_name": text().notNull(),
    "effective_threshold": real().notNull(),
    "threshold_source": text().notNull(),
    "current_average": real(),
    "status": text().notNull(),
    "priority": text().notNull(),
    "owner_name": text(),
    "planned_action": text(),
    "notes": text(),
    "follow_up_date": text(),
    "outcome": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "resolved_at": text(),
});
export const academic_master_audit = sqliteTable("academic_master_audit", {
    "id": integer().primaryKey(),
    "entity_type": text().notNull(),
    "entity_id": text().notNull(),
    "action": text().notNull(),
    "actor": text().notNull(),
    "before_data": text(),
    "after_data": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const academic_master_import_previews = sqliteTable("academic_master_import_previews", {
    "id": text().primaryKey(),
    "source_owner": text().notNull(),
    "created_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "status": text().notNull().default("review_required"),
    "proposed_data": text().notNull(),
    "validation_result": text().notNull(),
    "approved_by": text(),
    "approved_at": text(),
});
export const academic_programs = sqliteTable("academic_programs", {
    "id": integer().primaryKey(),
    "jenjang_id": integer().notNull(),
    "name": text().notNull(),
    "active": integer().notNull().default(1),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const academic_roster_import_batches = sqliteTable("academic_roster_import_batches", {
    "id": text().primaryKey(),
    "session_id": text().notNull(),
    "filename": text().notNull(),
    "checksum": text().notNull(),
    "source_owner": text().notNull(),
    "date_received": text().notNull(),
    "created_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "status": text().notNull().default("preview"),
    "rows": text().notNull(),
    "summary": text().notNull(),
    "committed_by": text(),
    "committed_at": text(),
    "commit_result": text(),
});
export const academic_term_configs = sqliteTable("academic_term_configs", {
    "id": integer().primaryKey(),
    "academic_year_id": integer().notNull(),
    "term_number": integer().notNull(),
    "label": text().notNull(),
    "start_date": text().notNull(),
    "end_date": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const academic_assessment_sessions = sqliteTable("academic_assessment_sessions", {
    "id": integer().primaryKey(),
    "academic_year_id": integer().notNull(),
    "term_number": integer().notNull(),
    "label": text().notNull(),
    "assessment_date": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const academic_years = sqliteTable("academic_years", {
    "id": integer().primaryKey(),
    "label": text().notNull(),
    "start_date": text().notNull(),
    "end_date": text().notNull(),
    "status": text().notNull(),
    "is_default": integer().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const assessment_components = sqliteTable("assessment_components", {
    "id": integer().primaryKey(),
    "name": text().notNull(),
    "assessment_type": text().notNull(),
    "subject_id": integer(),
});
export const attendance = sqliteTable("attendance", {
    "id": integer().primaryKey(),
    "student_id": integer().notNull(),
    "date": text().notNull(),
    "check_in": text(),
    "check_out": text(),
    "late_duration": integer().notNull(),
    "late_source": text().notNull(),
    "is_absent": integer().notNull(),
    "overtime": text(),
    "exception": text(),
    "week": text(),
    "status": text().notNull(),
});
export const attendance_calendar_exceptions = sqliteTable("attendance_calendar_exceptions", {
    "id": integer().primaryKey(),
    "academic_year_id": integer().notNull(),
    "jenjang_id": integer().notNull(),
    "date": text().notNull(),
    "expectation": text().notNull(),
    "reason": text().notNull(),
    "created_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const attendance_calendar_weekday_rules = sqliteTable("attendance_calendar_weekday_rules", {
    "id": integer().primaryKey(),
    "academic_year_id": integer().notNull(),
    "jenjang_id": integer().notNull(),
    "weekday": integer().notNull(),
    "expectation": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const attendance_correction_audit = sqliteTable("attendance_correction_audit", {
    "id": integer().primaryKey(),
    "request_id": integer().notNull(),
    "action": text().notNull(),
    "prior_state": text(),
    "new_state": text().notNull(),
    "actor": text().notNull(),
    "effective_date": text().notNull(),
    "reason_code": text(),
    "explanation_summary": text(),
    "source_workflow": text().notNull(),
    "metadata_version": integer().notNull(),
    "created_at": text().notNull(),
});
export const attendance_correction_requests = sqliteTable("attendance_correction_requests", {
    "id": integer().primaryKey(),
    "attendance_id": integer().notNull(),
    "active_key": text(),
    "original_snapshot": text().notNull(),
    "original_fingerprint": text().notNull(),
    "proposed_status": text().notNull(),
    "proposed_check_in": text(),
    "proposed_check_out": text(),
    "reason_code": text().notNull(),
    "explanation": text().notNull(),
    "requester": text().notNull(),
    "submitted_at": text(),
    "state": text().notNull().default("DRAFT"),
    "version": integer().notNull().default(1),
    "approver": text(),
    "decided_at": text(),
    "rejection_reason": text(),
    "resulting_override_id": integer(),
    "created_at": text().notNull(),
    "updated_at": text().notNull(),
});
export const attendance_follow_up_audit = sqliteTable("attendance_follow_up_audit", {
    "id": integer().primaryKey(),
    "follow_up_id": integer(),
    "actor": text().notNull(),
    "action": text().notNull(),
    "before_summary": text(),
    "after_summary": text(),
    "metadata_payload": text(),
    "timestamp": text().notNull(),
    "schema_version": integer().notNull(),
});
export const attendance_follow_up_notes = sqliteTable("attendance_follow_up_notes", {
    "id": integer().primaryKey(),
    "follow_up_id": integer().notNull(),
    "note_type": text().notNull(),
    "body": text().notNull(),
    "created_by_user_id": integer().notNull(),
    "created_at": text().notNull(),
    "supersedes_note_id": integer(),
});
export const attendance_follow_ups = sqliteTable("attendance_follow_ups", {
    "id": integer().primaryKey(),
    "exception_key": text().notNull(),
    "exception_kind": text().notNull(),
    "student_master_id": text(),
    "student_enrollment_id": integer(),
    "attendance_id": integer(),
    "attendance_correction_request_id": integer(),
    "early_departure_excuse_id": integer(),
    "academic_class_id": integer(),
    "academic_year_id": integer(),
    "exception_date": text(),
    "period_start": text(),
    "period_end": text(),
    "source_snapshot": text(),
    "status": text().notNull(),
    "priority": text().notNull(),
    "assigned_to_user_id": integer(),
    "created_by_user_id": integer(),
    "acknowledged_by_user_id": integer(),
    "acknowledged_at": text(),
    "resolved_by_user_id": integer(),
    "resolved_at": text(),
    "resolution_code": text(),
    "resolution_note": text(),
    "due_at": text(),
    "version": integer().notNull(),
    "created_at": text().notNull(),
    "updated_at": text().notNull(),
});
export const attendance_import_batches = sqliteTable("attendance_import_batches", {
    "id": text().primaryKey(),
    "filename": text().notNull(),
    "checksum": text().notNull(),
    "uploaded_by": text().notNull(),
    "uploaded_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "status": text().notNull().default("preview"),
    "total_rows": integer().notNull().default(0),
    "logical_rows": integer().notNull().default(0),
    "new_records": integer().notNull().default(0),
    "update_records": integer().notNull().default(0),
    "unchanged_records": integer().notNull().default(0),
    "conflict_records": integer().notNull().default(0),
    "invalid_records": integer().notNull().default(0),
    "new_students": integer().notNull().default(0),
    "committed_at": text(),
    "commit_result": text(),
});
export const attendance_import_rows = sqliteTable("attendance_import_rows", {
    "id": integer().primaryKey(),
    "batch_id": text().notNull(),
    "source_row": integer(),
    "student_identifier": text(),
    "student_name": text(),
    "attendance_date": text(),
    "existing_attendance_id": integer(),
    "classification": text().notNull(),
    "existing_record": text(),
    "proposed_change": text(),
    "validation_error": text(),
    "warning": text(),
    "selected_for_commit": integer().notNull().default(0),
});
export const attendance_override_history = sqliteTable("attendance_override_history", {
    "id": integer().primaryKey(),
    "override_id": integer().notNull(),
    "attendance_id": integer().notNull(),
    "previous_status": text(),
    "new_status": text().notNull(),
    "previous_values": text(),
    "new_values": text(),
    "note": text().notNull(),
    "reviewed_by": text().notNull(),
    "timestamp": text().notNull(),
});
export const attendance_overrides = sqliteTable("attendance_overrides", {
    "id": integer().primaryKey(),
    "attendance_id": integer().notNull(),
    "original_status": text().notNull(),
    "override_status": text().notNull(),
    "override_check_in": text(),
    "override_check_out": text(),
    "note": text().notNull(),
    "reviewed_by": text().notNull(),
    "reviewed_at": text().notNull(),
});
export const attendance_period_audit = sqliteTable("attendance_period_audit", {
    "id": integer().primaryKey(),
    "period_id": integer().notNull(),
    "action": text().notNull(),
    "prior_status": text().notNull(),
    "new_status": text().notNull(),
    "actor": text().notNull(),
    "reason": text().notNull(),
    "prior_version": integer().notNull(),
    "new_version": integer().notNull(),
    "created_at": text().notNull(),
});
export const attendance_periods = sqliteTable("attendance_periods", {
    "id": integer().primaryKey(),
    "attendance_date": text().notNull(),
    "status": text().notNull().default("OPEN"),
    "finalized_by": text(),
    "finalized_at": text(),
    "reason": text(),
    "version": integer().notNull().default(1),
    "reopened_by": text(),
    "reopened_at": text(),
});
export const backup_execution_history = sqliteTable("backup_execution_history", {
    "id": integer().primaryKey(),
    "backup_filename": text(),
    "started_at": text().notNull(),
    "completed_at": text(),
    "duration_seconds": real(),
    "status": text().notNull(),
    "error_message": text(),
    "trigger_type": text().notNull(),
    "size_bytes": integer(),
    "checksum": text(),
    "integrity_verified": integer().notNull().default(0),
    "removed_backups_json": text().notNull().default("[]"),
});
export const backup_scheduler_config = sqliteTable("backup_scheduler_config", {
    "id": integer().primaryKey(),
    "enabled": integer().notNull().default(0),
    "schedule_type": text().notNull().default("daily"),
    "interval_minutes": integer().notNull().default(1440),
    "hour_utc": integer().notNull().default(1),
    "minute_utc": integer().notNull().default(0),
    "weekday_utc": integer().notNull().default(0),
    "keep_daily": integer().notNull().default(7),
    "keep_weekly": integer().notNull().default(4),
    "keep_monthly": integer().notNull().default(12),
    "next_run_at": text(),
    "updated_at": text().notNull(),
});
export const dismissal_policies = sqliteTable("dismissal_policies", {
    "id": integer().primaryKey(),
    "jenjang_id": integer(),
    "jenjang": text().notNull(),
    "weekday": integer().notNull(),
    "dismissal_time": text().notNull(),
    "grace_period_minutes": integer().notNull(),
    "effective_from": text().notNull(),
    "effective_to": text(),
    "is_active": integer().notNull(),
    "change_reason": text(),
    "created_by": text().notNull(),
    "created_at": text().notNull(),
    "updated_at": text().notNull(),
});
export const dismissal_policy_audits = sqliteTable("dismissal_policy_audits", {
    "id": integer().primaryKey(),
    "policy_id": integer().notNull(),
    "action": text().notNull(),
    "change_reason": text(),
    "actor": text().notNull(),
    "timestamp": text().notNull(),
    "policy_snapshot": text(),
});
export const early_departure_excuse_audits = sqliteTable("early_departure_excuse_audits", {
    "id": integer().primaryKey(),
    "excuse_id": integer().notNull(),
    "action": text().notNull(),
    "actor": text().notNull(),
    "timestamp": text().notNull(),
    "reason_code": text(),
    "revocation_reason": text(),
});
export const early_departure_excuses = sqliteTable("early_departure_excuses", {
    "id": integer().primaryKey(),
    "attendance_id": integer().notNull(),
    "reason_code": text().notNull(),
    "explanation": text(),
    "state": text().notNull(),
    "recorded_by": text().notNull(),
    "recorded_at": text().notNull(),
    "revoked_by": text(),
    "revoked_at": text(),
    "revocation_reason": text(),
});
export const enrollment_population_preview_batches = sqliteTable("enrollment_population_preview_batches", {
    "id": text().primaryKey(),
    "academic_year_id": integer().notNull(),
    "effective_start_date": text().notNull(),
    "snapshot_checksum": text().notNull(),
    "rows": text().notNull(),
    "created_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "committed_at": text(),
});
export const first_admin_setup_state = sqliteTable("first_admin_setup_state", {
    "id": integer().primaryKey(),
    "completed": integer().notNull().default(0),
    "completed_at": text(),
    "created_user_id": integer(),
    "normalized_username": text(),
    "provisioning_source": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const heb_overrides = sqliteTable("heb_overrides", {
    "id": integer().primaryKey(),
    "jenjang": text().notNull(),
    "month": integer().notNull(),
    "year": integer().notNull(),
    "heb_value": integer().notNull(),
    "note": text(),
    "set_by": text().notNull(),
    "set_at": text().notNull(),
});
export const jenjang_config = sqliteTable("jenjang_config", {
    "id": integer().primaryKey(),
    "jenjang": text().notNull(),
    "cutoff_time": text().notNull(),
    "updated_at": text().notNull(),
});
export const jenjangs = sqliteTable("jenjangs", {
    "id": integer().primaryKey(),
    "name": text().notNull(),
    "code": text(),
    "level": text(),
    "active": integer().notNull().default(1),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const kkm_thresholds = sqliteTable("kkm_thresholds", {
    "id": integer().primaryKey(),
    "academic_year_id": integer().notNull(),
    "jenjang_id": integer(),
    "subject_id": integer(),
    "assessment_type": text().notNull(),
    "threshold": real().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const legacy_link_preview_batches = sqliteTable("legacy_link_preview_batches", {
    "id": text().primaryKey(),
    "snapshot_checksum": text().notNull(),
    "rows": text().notNull(),
    "created_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "committed_at": text(),
});
export const legacy_link_resolutions = sqliteTable("legacy_link_resolutions", {
    "id": integer().primaryKey(),
    "legacy_student_id": integer().notNull(),
    "resolution": text().notNull(),
    "student_master_id": text(),
    "reason": text().notNull(),
    "resolved_by": text().notNull(),
    "resolved_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const operations_audit_events = sqliteTable("operations_audit_events", {
    "id": integer().primaryKey(),
    "event_id": text().notNull(),
    "occurred_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "actor_id": text().notNull(),
    "actor_role": text().notNull(),
    "capability": text().notNull(),
    "entity_type": text().notNull(),
    "entity_reference": text().notNull(),
    "operation": text().notNull(),
    "risk_level": text().notNull(),
    "source": text().notNull(),
    "reason": text(),
    "import_session_id": text(),
    "import_action_id": integer(),
    "rollback_action_id": integer(),
    "export_scope": text(),
    "success": integer().notNull(),
    "failure_code": text(),
    "changed_fields": text(),
    "request_correlation_id": text(),
    "metadata": text().notNull(),
    "schema_version": text().notNull(),
});
export const operatoros_schema_migrations = sqliteTable("operatoros_schema_migrations", {
    "version": text().primaryKey(),
    "predecessor": text(),
    "schema_fingerprint": text().notNull(),
    "protected_fingerprints": text().notNull(),
    "approved_by": text().notNull(),
    "applied_at": text().notNull(),
});
export const report_branding_configs = sqliteTable("report_branding_configs", {
    "id": integer().primaryKey(),
    "school_name": text().notNull(),
    "foundation_name": text(),
    "report_header_title": text().notNull(),
    "report_subtitle": text().notNull(),
    "primary_color": text().notNull(),
    "secondary_color": text().notNull(),
    "accent_color": text().notNull(),
    "logo_path": text(),
    "logo_label": text(),
    "footer_text": text().notNull(),
    "prepared_by": text().notNull(),
    "is_default": integer().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const report_templates = sqliteTable("report_templates", {
    "id": integer().primaryKey(),
    "name": text().notNull(),
    "description": text(),
    "template_type": text().notNull(),
    "output_format": text().notNull(),
    "is_default": integer().notNull(),
    "is_active": integer().notNull(),
    "page_order_json": text().notNull(),
    "section_visibility_json": text().notNull(),
    "chart_visibility_json": text().notNull(),
    "excel_sheet_visibility_json": text().notNull(),
    "default_filters_json": text().notNull(),
    "export_options_json": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const sessions = sqliteTable("sessions", {
    "id": integer().primaryKey(),
    "user_id": integer().notNull(),
    "token_hash": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "last_used_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "expires_at": text().notNull(),
    "absolute_expires_at": text().notNull(),
    "revoked_at": text(),
    "user_agent": text(),
    "ip_address": text(),
});
export const staff_contact_details = sqliteTable("staff_contact_details", {
    "id": integer().primaryKey(),
    "staff_member_id": text().notNull(),
    "address": text(),
    "email": text(),
    "phone": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const staff_education = sqliteTable("staff_education", {
    "id": integer().primaryKey(),
    "staff_member_id": text().notNull(),
    "education_level": text().notNull(),
    "institution_name": text().notNull(),
    "major": text(),
    "graduation_year": integer(),
    "notes": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const staff_identifiers = sqliteTable("staff_identifiers", {
    "id": integer().primaryKey(),
    "staff_member_id": text().notNull(),
    "identifier_type": text().notNull(),
    "raw_value": text(),
    "normalized_value": text(),
    "verification_status": text().notNull().default("UNVERIFIED"),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const staff_import_batches = sqliteTable("staff_import_batches", {
    "id": text().primaryKey(),
    "source_filename": text().notNull(),
    "source_sheet": text().notNull(),
    "file_sha256": text().notNull(),
    "imported_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "imported_by_user_id": integer(),
    "actor": text().notNull().default("staff-import-cli"),
    "total_rows": integer().notNull().default(0),
    "active_count": integer().notNull().default(0),
    "former_count": integer().notNull().default(0),
    "review_count": integer().notNull().default(0),
    "issue_count": integer().notNull().default(0),
    "status": text().notNull().default("APPLIED"),
    "notes": text(),
});
export const staff_import_issues = sqliteTable("staff_import_issues", {
    "id": integer().primaryKey(),
    "batch_id": text().notNull(),
    "import_row_id": integer(),
    "issue_code": text().notNull(),
    "field_name": text(),
    "severity": text().notNull().default("WARNING"),
    "message": text().notNull(),
    "resolved_at": text(),
    "resolved_by_user_id": integer(),
    "resolution_notes": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const staff_import_rows = sqliteTable("staff_import_rows", {
    "id": integer().primaryKey(),
    "batch_id": text().notNull(),
    "source_row_number": integer().notNull(),
    "source_staff_id": text(),
    "staff_member_id": text(),
    "raw_payload_json": text().notNull(),
    "normalized_payload_json": text().notNull(),
    "row_status": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const staff_jenjang_assignments = sqliteTable("staff_jenjang_assignments", {
    "staff_member_id": text().primaryKey(),
    "jenjang_id": integer().primaryKey(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const staff_job_title_mappings = sqliteTable("staff_job_title_mappings", {
    "id": integer().primaryKey(),
    "raw_title": text().notNull(),
    "normalized_title": text().notNull(),
    "status": text().notNull().default("PENDING"),
    "approved_by_user_id": integer(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const staff_members = sqliteTable("staff_members", {
    "id": text().primaryKey(),
    "source_staff_id": text(),
    "full_name": text().notNull(),
    "normalized_name": text().notNull(),
    "employment_status": text().notNull().default("UNKNOWN"),
    "birth_place": text(),
    "birth_date": text(),
    "job_title_raw": text(),
    "job_title_normalized": text(),
    "employment_start_date": text(),
    "employment_end_date": text(),
    "dapodik_status_raw": text(),
    "dapodik_status_normalized": text().notNull().default("UNKNOWN"),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_academic_mapping_rules = sqliteTable("student_academic_mapping_rules", {
    "id": integer().primaryKey(),
    "mapping_type": text().notNull(),
    "source_value": text().notNull(),
    "normalized_source_value": text().notNull(),
    "target_value": text(),
    "target_id": integer(),
    "status": text().notNull().default("draft"),
    "created_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "approved_by": text(),
    "approved_at": text(),
});
export const student_addresses = sqliteTable("student_addresses", {
    "id": integer().primaryKey(),
    "student_master_id": text().notNull(),
    "address": text(),
    "kelurahan": text(),
    "kecamatan": text(),
    "city_regency": text(),
    "province": text(),
    "postal_code": text(),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_contacts = sqliteTable("student_contacts", {
    "id": integer().primaryKey(),
    "student_master_id": text().notNull(),
    "student_phone": text(),
    "student_email": text(),
    "emergency_contact_name": text(),
    "emergency_contact_relationship": text(),
    "emergency_contact_phone": text(),
    "emergency_contact_address": text(),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_device_identities = sqliteTable("student_device_identities", {
    "id": integer().primaryKey(),
    "student_master_id": text().notNull(),
    "legacy_student_id": integer(),
    "device_identifier": text().notNull(),
    "device_source": text().notNull(),
    "effective_from": text().notNull(),
    "effective_to": text(),
    "is_active": integer().notNull().default(1),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "created_by": text(),
});
export const student_document_statuses = sqliteTable("student_document_statuses", {
    "id": integer().primaryKey(),
    "student_master_id": text().notNull(),
    "family_card_received": integer().notNull().default(0),
    "birth_certificate_received": integer().notNull().default(0),
    "parent_id_received": integer().notNull().default(0),
    "school_agreement_received": integer().notNull().default(0),
    "publication_consent_received": integer().notNull().default(0),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_enrollment_class_history = sqliteTable("student_enrollment_class_history", {
    "id": integer().primaryKey(),
    "enrollment_id": integer().notNull(),
    "class_name": text(),
    "effective_from": text().notNull(),
    "effective_to": text(),
    "changed_by": text().notNull(),
    "changed_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "source": text().notNull(),
    "import_batch_id": text(),
});
export const student_enrollment_lifecycle_audit = sqliteTable("student_enrollment_lifecycle_audit", {
    "id": integer().primaryKey(),
    "enrollment_id": integer().notNull(),
    "prior_state": text().notNull(),
    "new_state": text().notNull(),
    "effective_date": text().notNull(),
    "actor": text().notNull(),
    "reason_code": text().notNull(),
    "source_workflow": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_enrollments = sqliteTable("student_enrollments", {
    "id": integer().primaryKey(),
    "student_id": integer(),
    "student_master_id": text(),
    "academic_year_id": integer().notNull(),
    "jenjang_id": integer().notNull(),
    "academic_class_id": integer(),
    "class_name": text(),
    "class_assigned": integer().notNull(),
    "effective_from": text(),
    "effective_to": text(),
    "lifecycle_state": text().notNull().default("ACTIVE"),
    "lifecycle_effective_date": text(),
    "lifecycle_reason_code": text(),
    "lifecycle_reason": text(),
    "dapodik_registrasi_id": text(),
    "dapodik_anggota_rombel_id": text(),
    "dapodik_sekolah_id": text(),
    "dapodik_semester_id": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_health_profiles = sqliteTable("student_health_profiles", {
    "id": integer().primaryKey(),
    "student_master_id": text().notNull(),
    "allergy": text(),
    "medical_condition": text(),
    "special_needs": text(),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_import_applied_actions = sqliteTable("student_import_applied_actions", {
    "id": integer().primaryKey(),
    "session_id": text().notNull(),
    "student_import_batch_id": text(),
    "academic_roster_import_batch_id": text(),
    "source_row_number": integer().notNull(),
    "action_sequence": integer().notNull(),
    "action_type": text().notNull(),
    "entity_type": text().notNull(),
    "entity_id": text().notNull(),
    "entity_reference": text().notNull(),
    "operation_id": text().notNull(),
    "parent_action_id": integer(),
    "applied_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "applied_by": text().notNull(),
    "request_correlation_id": text(),
    "before_state": text(),
    "after_state": text().notNull(),
    "before_state_checksum": text(),
    "after_state_checksum": text().notNull(),
    "dependency_checkpoint": text().notNull(),
    "compensation_type": text().notNull(),
    "rollback_eligibility": text().notNull(),
    "rollback_block_reason": text(),
    "rollback_state": text().notNull(),
    "rollback_action_id": integer(),
    "metadata": text().notNull(),
    "schema_version": text().notNull(),
});
export const student_import_batches = sqliteTable("student_import_batches", {
    "id": text().primaryKey(),
    "session_id": text().notNull(),
    "filename": text().notNull(),
    "file_checksum": text().notNull(),
    "source_sheet": text(),
    "status": text().notNull().default("preview"),
    "total_rows": integer().notNull().default(0),
    "new_count": integer().notNull().default(0),
    "update_count": integer().notNull().default(0),
    "unchanged_count": integer().notNull().default(0),
    "conflict_count": integer().notNull().default(0),
    "invalid_count": integer().notNull().default(0),
    "created_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "committed_at": text(),
});
export const student_import_rows = sqliteTable("student_import_rows", {
    "id": integer().primaryKey(),
    "batch_id": text().notNull(),
    "source_row": integer().notNull(),
    "classification": text().notNull(),
    "matched_student_master_id": text(),
    "normalized_payload": text().notNull(),
    "differences": text().notNull(),
    "validation_errors": text().notNull(),
    "selected_for_commit": integer().notNull().default(0),
});
export const student_import_sessions = sqliteTable("student_import_sessions", {
    "id": text().primaryKey(),
    "session_uuid": text().notNull(),
    "import_type": text().notNull(),
    "status": text().notNull(),
    "provenance_status": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "created_by": text().notNull(),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "committed_at": text(),
    "committed_by": text(),
    "expires_at": text().notNull(),
    "source_filename": text().notNull(),
    "source_file_checksum": text().notNull(),
    "preview_checksum": text(),
    "commit_checksum": text(),
    "idempotency_key": text(),
    "request_correlation_id": text(),
    "row_count": integer().notNull(),
    "selected_row_count": integer().notNull(),
    "applied_action_count": integer().notNull(),
    "rollback_state": text().notNull(),
    "rollback_requested_at": text(),
    "rollback_completed_at": text(),
    "metadata": text().notNull(),
    "schema_version": text().notNull(),
});
export const student_master_change_history = sqliteTable("student_master_change_history", {
    "id": integer().primaryKey(),
    "student_master_id": text().notNull(),
    "action": text().notNull(),
    "field_name": text(),
    "old_value": text(),
    "new_value": text(),
    "source": text().notNull(),
    "import_batch_id": text(),
    "changed_by": text().notNull(),
    "changed_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_masters = sqliteTable("student_masters", {
    "id": text().primaryKey(),
    "full_name": text().notNull(),
    "normalized_name": text().notNull(),
    "preferred_name": text(),
    "nipd": text(),
    "nisn": text(),
    "nik": text(),
    "gender": text(),
    "birth_place": text(),
    "birth_date": text(),
    "religion": text(),
    "citizenship": text(),
    "blood_type": text(),
    "student_status": text().notNull().default("pending_review"),
    "admission_date": text(),
    "admission_type": text(),
    "previous_school": text(),
    "dapodik_peserta_didik_id": text(),
    "dapodik_sekolah_id": text(),
    "dapodik_last_update_at": text(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "created_by": text(),
    "updated_by": text(),
});
export const student_parent_guardians = sqliteTable("student_parent_guardians", {
    "id": integer().primaryKey(),
    "student_master_id": text().notNull(),
    "guardian_type": text().notNull(),
    "name": text().notNull(),
    "phone": text(),
    "email": text(),
    "occupation": text(),
    "education": text(),
    "address": text(),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_progression_audit = sqliteTable("student_progression_audit", {
    "id": integer().primaryKey(),
    "batch_id": text().notNull(),
    "preview_row_id": integer().notNull(),
    "source_enrollment_id": integer().notNull(),
    "destination_enrollment_id": integer(),
    "student_master_id": text().notNull(),
    "outcome": text().notNull(),
    "reason_code": text().notNull(),
    "mapping_source": text().notNull(),
    "source_context": text().notNull(),
    "destination_context": text(),
    "actor": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_progression_mapping_rules = sqliteTable("student_progression_mapping_rules", {
    "id": integer().primaryKey(),
    "source_jenjang_id": integer().notNull(),
    "destination_jenjang_id": integer().notNull(),
    "source_program_id": integer().notNull(),
    "destination_program_id": integer().notNull(),
    "source_grade_id": integer().notNull(),
    "destination_grade_id": integer().notNull(),
    "outcome": text().notNull(),
    "active": integer().notNull().default(1),
    "created_by": text().notNull(),
    "approved_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const student_progression_preview_batches = sqliteTable("student_progression_preview_batches", {
    "id": text().primaryKey(),
    "source_academic_year_id": integer().notNull(),
    "destination_academic_year_id": integer().notNull(),
    "status": text().notNull().default("PREVIEW"),
    "preview_version": integer().notNull().default(1),
    "snapshot_checksum": text().notNull(),
    "rows": text().notNull(),
    "summary": text().notNull(),
    "created_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "committed_by": text(),
    "committed_at": text(),
    "commit_result": text(),
});
export const student_subject_grades = sqliteTable("student_subject_grades", {
    "id": integer().primaryKey(),
    "enrollment_id": integer().notNull(),
    "subject_id": integer().notNull(),
    "component_id": integer().notNull(),
    "assessment_session_id": integer(),
    "score": real(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const students = sqliteTable("students", {
    "id": integer().primaryKey(),
    "name": text().notNull(),
    "jenjang": text(),
    "class_name": text(),
    "id_updated_at": text(),
});
export const subjects = sqliteTable("subjects", {
    "id": integer().primaryKey(),
    "name": text().notNull(),
    "jenjang_id": integer().notNull(),
    "supports_sumatif": integer().notNull(),
    "supports_formatif": integer().notNull(),
});
export const teacher_class_assignment_audit = sqliteTable("teacher_class_assignment_audit", {
    "id": integer().primaryKey(),
    "assignment_id": integer(),
    "user_id": integer(),
    "academic_class_id": integer(),
    "academic_year_id": integer(),
    "target_date": text(),
    "action": text().notNull(),
    "actor": text().notNull(),
    "before_summary": text(),
    "after_summary": text(),
    "source_workflow": text().notNull().default("TEACHER_CLASS_ASSIGNMENT"),
    "metadata_version": integer().notNull().default(1),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const teacher_class_assignments = sqliteTable("teacher_class_assignments", {
    "id": integer().primaryKey(),
    "user_id": integer().notNull(),
    "academic_year_id": integer().notNull(),
    "academic_class_id": integer().notNull(),
    "class_role": text().notNull(),
    "subject_id": integer(),
    "effective_from": text(),
    "effective_to": text(),
    "active": integer().notNull().default(1),
    "assigned_by": text().notNull(),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const upload_logs = sqliteTable("upload_logs", {
    "id": integer().primaryKey(),
    "filename": text().notNull(),
    "uploaded_at": text().notNull(),
    "uploaded_by": text(),
    "total_records": integer().notNull(),
    "new_students": integer().notNull(),
    "late_entries": integer().notNull(),
    "incomplete_entries": integer().notNull(),
    "failed_rows": integer().notNull(),
    "skipped_empty": integer().notNull(),
    "status": text().notNull(),
});
export const users = sqliteTable("users", {
    "id": integer().primaryKey(),
    "username": text().notNull(),
    "password_hash": text().notNull(),
    "role": text().notNull(),
    "is_active": integer().notNull().default(1),
    "created_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "updated_at": text().notNull().default(sql`CURRENT_TIMESTAMP`),
    "last_login_at": text(),
    "failed_login_attempts": integer().notNull().default(0),
    "locked_until": text(),
});
