from __future__ import annotations

from datetime import date
from io import BytesIO
from typing import Iterable

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


PDF_MIME = "application/pdf"
XLSX_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
SCHOOL_NAME = "EDELWEISS SCHOOL"
REPORT_TITLE = "Management Analytics Report"
REPORT_SUBTITLE = "Attendance, Lateness, Academic Performance, and Below-KKM Summary"

_THIN_BORDER = Border(
    left=Side(style="thin", color="D1D5DB"),
    right=Side(style="thin", color="D1D5DB"),
    top=Side(style="thin", color="D1D5DB"),
    bottom=Side(style="thin", color="D1D5DB"),
)
_HEADER_FILL = PatternFill("solid", fgColor="E2E8F0")


def _term_label(term: str | None) -> str:
    labels = {
        "term_1": "Term 1",
        "term_2": "Term 2",
        "term_3": "Term 3",
        "term_4": "Term 4",
    }
    return labels.get(term or "", "All")


def build_management_report_filename(summary: dict, extension: str, printed_date: date | None = None) -> str:
    filters = summary["filters"]
    academic_year = (filters.get("academic_year_label") or "all-years").replace("/", "-")
    term = (filters.get("term") or "all-terms").replace("_", "-")
    report_date = (printed_date or date.today()).isoformat()
    return f"management-analytics-report-{academic_year}-{term}-{report_date}.{extension}"


def build_report_context(summary: dict, printed_date: date | None = None) -> list[tuple[str, str]]:
    filters = summary["filters"]
    return [
        ("School Name", SCHOOL_NAME),
        ("Report Title", REPORT_TITLE),
        ("Printed Date", (printed_date or date.today()).isoformat()),
        ("Academic Year", filters.get("academic_year_label") or "All"),
        ("Jenjang", filters.get("jenjang_name") or "All"),
        ("Class Filter", filters.get("class_name") or "All"),
        ("Subject Filter", filters.get("subject_name") or "All"),
        ("Term Filter", _term_label(filters.get("term"))),
        ("Generated By System", "Yes"),
    ]


def _display(value) -> str:
    if value is None:
        return "-"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    return str(value)


def _rows_for_pdf(summary: dict) -> list[str]:
    attendance = summary["attendance_summary"]
    lines = [
        SCHOOL_NAME,
        REPORT_TITLE,
        REPORT_SUBTITLE,
        "",
        "Report Header",
    ]
    lines.extend(f"{label}: {value}" for label, value in build_report_context(summary))
    lines.extend(
        [
            "",
            "Executive Summary KPIs",
            f"Attendance percentage: {attendance['status_percentages']['hadir']}%",
            f"Total records: {attendance['total_records']}",
            f"Late days: {sum(row['late_days'] for row in summary['lateness_by_class'])}",
            f"Below-KKM alerts: {len(summary.get('below_kkm_alerts', []))}",
            "",
            "Attendance Summary",
            f"Hadir: {attendance['status_counts']['hadir']}",
            f"Sakit: {attendance['status_counts']['sakit']}",
            f"Izin: {attendance['status_counts']['izin']}",
            f"Alfa: {attendance['status_counts']['alfa']}",
            f"Attendance percentage: {attendance['status_percentages']['hadir']}%",
            "",
            "Lateness by Class",
        ]
    )

    if summary["lateness_by_class"]:
        for row in summary["lateness_by_class"][:24]:
            lines.append(
                f"{row['class_name']} | late days {row['late_days']} | minutes {row['late_minutes']} "
                f"| duration {row['late_duration_label']} | day {row['late_day_percentage']}% "
                f"| minutes {row['late_duration_percentage']}%"
            )
    else:
        lines.append("No lateness records.")

    lines.extend(["", "Grade by Class"])
    if summary["grade_by_class"]:
        for row in summary["grade_by_class"][:24]:
            subject_context = row.get("subject_context") or "All"
            lines.append(
                f"{row['class_name']} | Sumatif {_display(row['sumatif_average'])} | "
                f"Formatif {_display(row['formatif_average'])} | Students {row['student_count']} | "
                f"Subject {subject_context}"
            )
    else:
        lines.append("No class grade records.")

    lines.extend(["", "Grade by Subject"])
    if summary["grade_by_subject"]:
        for row in summary["grade_by_subject"][:24]:
            lines.append(
                f"{row['subject_name']} | Jenjang {row.get('jenjang') or '-'} | "
                f"Sumatif {_display(row['sumatif_average'])} | Formatif {_display(row['formatif_average'])} | "
                f"Students {row.get('graded_student_count', 0)}"
            )
    else:
        lines.append("No subject grade records.")

    lines.extend(["", "Grade by Student"])
    if summary["grade_by_student"]:
        for row in summary["grade_by_student"][:30]:
            lines.append(
                f"{row['student_name']} | {row['class_name']} | {row.get('subject_name') or '-'} | "
                f"Sumatif {_display(row['sumatif_average'])} | Formatif {_display(row['formatif_average'])} | "
                f"Below KKM {_display(row['below_threshold'])}"
            )
        if len(summary["grade_by_student"]) > 30:
            lines.append(f"PDF preview limited to 30 of {len(summary['grade_by_student'])} student rows.")
    else:
        lines.append("No student grade records.")

    lines.extend(["", "Below-KKM Alerts"])
    if summary.get("below_kkm_alerts"):
        for row in summary["below_kkm_alerts"][:30]:
            lines.append(
                f"{row['student_name']} | {row['class_name']} | {row['subject_name']} | "
                f"{row['assessment_type']} | score {row['average_score']} | KKM {row['kkm_threshold']} | "
                f"gap {row['gap_from_threshold']}"
            )
        if len(summary["below_kkm_alerts"]) > 30:
            lines.append(f"PDF preview limited to 30 of {len(summary['below_kkm_alerts'])} alert rows.")
    else:
        lines.append("No Below-KKM alerts.")

    lines.extend(["", "Warnings and Limitations"])
    lines.extend(summary.get("warnings") or ["None"])
    lines.extend(["", "Generated by School Attendance Analytics."])
    return lines


def _escape_pdf_text(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _wrap_pdf_line(line: str, width: int = 112) -> Iterable[str]:
    text = line.strip()
    if not text:
        yield ""
        return

    while len(text) > width:
        split_at = text.rfind(" ", 0, width)
        if split_at <= 0:
            split_at = width
        yield text[:split_at]
        text = text[split_at:].strip()
    yield text


def _pdf_stream_lines(lines: list[str]) -> list[str]:
    stream_lines = ["BT", "/F1 9 Tf", "50 790 Td", "12 TL"]
    first = True
    for source_line in lines:
        for line in _wrap_pdf_line(source_line):
            if not first:
                stream_lines.append("T*")
            stream_lines.append(f"({_escape_pdf_text(line)}) Tj")
            first = False
    stream_lines.append("ET")
    return stream_lines


def build_management_summary_pdf(summary: dict) -> bytes:
    content = "\n".join(_pdf_stream_lines(_rows_for_pdf(summary))).encode("latin-1", errors="replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(content)).encode("ascii") + b" >>\nstream\n" + content + b"\nendstream",
    ]

    output = BytesIO()
    output.write(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(output.tell())
        output.write(f"{index} 0 obj\n".encode("ascii"))
        output.write(obj)
        output.write(b"\nendobj\n")
    xref_offset = output.tell()
    output.write(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.write(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.write(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("ascii")
    )
    return output.getvalue()


def _append_table(sheet, title: str, headers: list[str], rows: list[list]):
    sheet.append([title])
    title_row = sheet.max_row
    sheet.cell(title_row, 1).font = Font(bold=True, size=13)
    sheet.append(headers)
    header_row = sheet.max_row
    for column in range(1, len(headers) + 1):
        cell = sheet.cell(header_row, column)
        cell.font = Font(bold=True)
        cell.fill = _HEADER_FILL
        cell.border = _THIN_BORDER
        cell.alignment = Alignment(horizontal="center")
    for row in rows:
        sheet.append(row)
        for column in range(1, len(headers) + 1):
            sheet.cell(sheet.max_row, column).border = _THIN_BORDER
    sheet.append([])


def _fit_columns(sheet):
    for column_cells in sheet.columns:
        max_length = 0
        column_letter = get_column_letter(column_cells[0].column)
        for cell in column_cells:
            max_length = max(max_length, len(_display(cell.value)))
        sheet.column_dimensions[column_letter].width = min(max(max_length + 2, 12), 42)


def build_management_summary_excel(summary: dict) -> bytes:
    workbook = Workbook()
    summary_sheet = workbook.active
    summary_sheet.title = "Summary"

    summary_sheet.append([REPORT_TITLE])
    summary_sheet.cell(1, 1).font = Font(bold=True, size=16)
    summary_sheet.append([REPORT_SUBTITLE])
    summary_sheet.append([])
    for label, value in build_report_context(summary):
        summary_sheet.append([label, value])
    summary_sheet.append([])
    attendance = summary["attendance_summary"]
    summary_sheet.append(["Attendance percentage", attendance["status_percentages"]["hadir"]])
    summary_sheet.append(["Total records", attendance["total_records"]])
    summary_sheet.append(["Late days", sum(row["late_days"] for row in summary["lateness_by_class"])])
    summary_sheet.append(["Below-KKM alerts", len(summary.get("below_kkm_alerts", []))])

    attendance_sheet = workbook.create_sheet("Attendance Summary")
    _append_table(
        attendance_sheet,
        "Attendance Summary",
        ["Status", "Total", "Percentage"],
        [
            ["Hadir", attendance["status_counts"]["hadir"], attendance["status_percentages"]["hadir"]],
            ["Sakit", attendance["status_counts"]["sakit"], attendance["status_percentages"]["sakit"]],
            ["Izin", attendance["status_counts"]["izin"], attendance["status_percentages"]["izin"]],
            ["Alfa", attendance["status_counts"]["alfa"], attendance["status_percentages"]["alfa"]],
            ["Total records", attendance["total_records"], ""],
        ],
    )

    lateness_sheet = workbook.create_sheet("Lateness by Class")
    _append_table(
        lateness_sheet,
        "Lateness by Class",
        ["Class name", "Late days", "Total late minutes", "Duration", "Late days %", "Late minutes %"],
        [
            [
                row["class_name"],
                row["late_days"],
                row["late_minutes"],
                row["late_duration_label"],
                row["late_day_percentage"],
                row["late_duration_percentage"],
            ]
            for row in summary["lateness_by_class"]
        ],
    )

    grade_class_sheet = workbook.create_sheet("Grade by Class")
    _append_table(
        grade_class_sheet,
        "Grade by Class",
        ["Class name", "Sumatif average", "Formatif average", "Student count", "Subject context"],
        [
            [
                row["class_name"],
                row["sumatif_average"],
                row["formatif_average"],
                row["student_count"],
                row.get("subject_context") or "All",
            ]
            for row in summary["grade_by_class"]
        ],
    )

    grade_subject_sheet = workbook.create_sheet("Grade by Subject")
    _append_table(
        grade_subject_sheet,
        "Grade by Subject",
        ["Subject name", "Jenjang", "Sumatif average", "Formatif average", "Graded student count"],
        [
            [
                row["subject_name"],
                row.get("jenjang") or "-",
                row["sumatif_average"],
                row["formatif_average"],
                row.get("graded_student_count", 0),
            ]
            for row in summary["grade_by_subject"]
        ],
    )

    grade_student_sheet = workbook.create_sheet("Grade by Student")
    _append_table(
        grade_student_sheet,
        "Grade by Student",
        ["Student name", "Class name", "Subject name", "Sumatif average", "Formatif average", "Below-KKM flag"],
        [
            [
                row["student_name"],
                row["class_name"],
                row.get("subject_name") or "-",
                row["sumatif_average"],
                row["formatif_average"],
                "Yes" if row["below_threshold"] else "No",
            ]
            for row in summary["grade_by_student"]
        ],
    )

    alert_sheet = workbook.create_sheet("Below-KKM Alerts")
    _append_table(
        alert_sheet,
        "Below-KKM Alerts",
        ["Student name", "Class name", "Subject name", "Assessment type", "Average score", "KKM threshold", "Gap"],
        [
            [
                row["student_name"],
                row["class_name"],
                row["subject_name"],
                row["assessment_type"],
                row["average_score"],
                row["kkm_threshold"],
                row["gap_from_threshold"],
            ]
            for row in summary.get("below_kkm_alerts", [])
        ],
    )

    warnings_sheet = workbook.create_sheet("Warnings")
    _append_table(warnings_sheet, "Warnings and Limitations", ["Warning"], [[warning] for warning in summary["warnings"]])

    for sheet in workbook.worksheets:
        _fit_columns(sheet)

    stream = BytesIO()
    workbook.save(stream)
    return stream.getvalue()
