export const ROUTE_GROUPS = {
  CORE: 'CORE',
  ATTENDANCE: 'ATTENDANCE',
  ACADEMIC: 'ACADEMIC',
  GRADES: 'GRADES',
  REPORTS_ANALYTICS: 'REPORTS_ANALYTICS',
  SYSTEM_ADMINISTRATION: 'SYSTEM_ADMINISTRATION',
} as const;

export type RouteGroup = (typeof ROUTE_GROUPS)[keyof typeof ROUTE_GROUPS];
