import type { StudentOverviewResponse } from "@operatoros/contracts/students";
import { Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Button, buttonVariants } from "../ui/button";
import { Alert, AlertDescription, AlertTitle } from "../ui/alert";

function value(input: number | null, unit = ""): string {
  return input === null ? "Not available" : `${input}${unit}`;
}

function Metrics({ values }: { values: Array<[string, string]> }) {
  return <dl className="grid grid-cols-2 gap-4 sm:grid-cols-3">{values.map(([label, item]) => <div key={label}><dt className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 text-lg font-black">{item}</dd></div>)}</dl>;
}

function Trend({ label, metric }: { label: string; metric: StudentOverviewResponse["trends"]["attendance"] }) {
  if (!metric || metric.previous === null || metric.current === null) return <div className="rounded-lg border border-border p-3"><h3 className="text-sm font-bold">{label}</h3><p className="mt-1 text-sm text-muted-foreground">Insufficient comparison data</p></div>;
  return <div className="rounded-lg border border-border p-3"><h3 className="text-sm font-bold">{label}</h3><p className="mt-1 text-lg font-black">{metric.previous}% → {metric.current}%</p><p className="text-xs text-muted-foreground">Delta {value(metric.delta, " pp")} · samples {metric.previousSampleSize} → {metric.currentSampleSize}</p></div>;
}

export function Student360Overview({ overview, exporting, exportError, onExport }: { overview: StudentOverviewResponse; exporting: boolean; exportError: string | null; onExport: () => void }) {
  const enrollment = overview.enrollment;
  return <div className="grid gap-4 lg:grid-cols-2">
    <Card className="lg:col-span-2"><CardHeader><CardTitle>Current student context</CardTitle></CardHeader><CardContent><Metrics values={[["Status", overview.student.status], ["Academic year", enrollment?.academicYear ?? "Not enrolled"], ["Jenjang", enrollment?.jenjang ?? "Not provided"], ["Class", enrollment?.className ?? "Not assigned"], ["Program", enrollment?.program ?? "Not provided"], ["Age", overview.student.ageYears === null ? "Not provided" : `${overview.student.ageYears} years`]]} /></CardContent></Card>

    <Card><CardHeader><CardTitle>Attendance</CardTitle></CardHeader><CardContent className="space-y-4">{overview.attendance.status === "unauthorized" ? <p className="text-sm text-muted-foreground">Attendance information is restricted for this account.</p> : overview.attendance.counts ? <><p className="text-xs text-muted-foreground">{overview.attendance.period?.start} – {overview.attendance.period?.end}</p><Metrics values={[["Attendance", value(overview.attendance.attendanceRate, "%")], ["Present", String(overview.attendance.counts.present)], ["Late", String(overview.attendance.counts.late)], ["Sakit", String(overview.attendance.counts.sakit)], ["Izin", String(overview.attendance.counts.izin)], ["Alfa", String(overview.attendance.counts.alfa)]]} /></> : <p className="text-sm text-muted-foreground">No attendance data is available for the current enrollment.</p>}<div className="flex flex-wrap gap-2">{overview.links.attendanceDetails && <Link className={buttonVariants({ size: "sm", variant: "outline" })} to={overview.links.attendanceDetails}>View attendance details</Link>}{overview.links.attendanceAnalytics && <Link className={buttonVariants({ size: "sm", variant: "outline" })} to={overview.links.attendanceAnalytics}>View attendance analytics</Link>}{overview.links.attendanceExport && <Button size="sm" variant="outline" onClick={onExport} disabled={exporting} aria-busy={exporting}>{exporting ? "Preparing workbook…" : "Export attendance history"}</Button>}</div>{exportError && <Alert variant="danger"><AlertTitle>Export failed</AlertTitle><AlertDescription>{exportError}</AlertDescription></Alert>}</CardContent></Card>

    <Card><CardHeader><CardTitle>Academic</CardTitle></CardHeader><CardContent className="space-y-4"><Metrics values={[["Average", value(overview.academic.average)], ["Participation", value(overview.academic.participation, "%")], ["Scored results", String(overview.academic.scoredResults)], ["Expected results", String(overview.academic.expectedResults)]]} /><p className="text-xs text-muted-foreground">Academic trend is unavailable because grade records do not yet have a trustworthy time or term axis.</p>{overview.links.academicAnalytics && <Link className={buttonVariants({ size: "sm", variant: "outline" })} to={overview.links.academicAnalytics}>View academic analytics</Link>}</CardContent></Card>

    <Card className="lg:col-span-2"><CardHeader><CardTitle>Attendance trends</CardTitle></CardHeader><CardContent className="space-y-4">{overview.trends.status === "unauthorized" ? <p className="text-sm text-muted-foreground">Trend information is restricted for this account.</p> : <><div className="grid gap-3 sm:grid-cols-3"><Trend label="Attendance" metric={overview.trends.attendance} /><Trend label="Tardiness" metric={overview.trends.tardiness} /><Trend label="Alfa" metric={overview.trends.alfa} /></div>{overview.trends.window && <p className="text-xs text-muted-foreground">Previous {overview.trends.window.previousStart ?? "unavailable"} – {overview.trends.window.previousEnd ?? "unavailable"}; current {overview.trends.window.currentStart} – {overview.trends.window.currentEnd}.</p>}{overview.links.trends && <Link className={buttonVariants({ size: "sm", variant: "outline" })} to={overview.links.trends}>View student trends</Link>}</>}</CardContent></Card>

    <Card><CardHeader><CardTitle>Data completeness</CardTitle></CardHeader><CardContent>{overview.dataCompleteness.issues.length ? <ul className="list-disc space-y-1 pl-5 text-sm">{overview.dataCompleteness.issues.map((issue) => <li key={`${issue.field}-${issue.type}`}>{issue.label}</li>)}</ul> : <p className="text-sm text-muted-foreground">No supported profile information is missing.</p>}{overview.links.dataQuality && <Link className={buttonVariants({ size: "sm", variant: "outline", className: "mt-4" })} to={overview.links.dataQuality}>View data quality</Link>}</CardContent></Card>

    <Card><CardHeader><CardTitle>Recent attendance history</CardTitle></CardHeader><CardContent>{overview.attendance.recent.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="pb-2 pr-4">Date</th><th className="pb-2 pr-4">Status</th><th className="pb-2">Time</th></tr></thead><tbody>{overview.attendance.recent.map((item) => <tr key={item.date} className="border-t border-border"><td className="py-2 pr-4">{item.date}</td><td className="py-2 pr-4">{item.status}{item.corrected ? " (corrected)" : ""}</td><td className="py-2">{item.checkIn ?? "—"} – {item.checkOut ?? "—"}</td></tr>)}</tbody></table></div> : <p className="text-sm text-muted-foreground">No recent attendance history is available.</p>}</CardContent></Card>
  </div>;
}
