import { addWorksheet, appendRow, createWorkbook, loadXlsxWorkbook, writeXlsxWorkbook, type ExcelWorkbook } from "@operatoros/excel";
import { createHash, randomUUID } from "node:crypto";
import { t } from "elysia";
import { inTransaction } from "@operatoros/db";
import { actor } from "./core";
import type { AuthContext } from "../auth/service";

type Row = Record<string, any>;
type Context = any;

const UPDATE_CONFIRMATION = "COMMIT_STUDENT_DATA_UPDATE";
const HEADERS = [
  "OperatorOS Student UUID", "Record Version", "Legal Name", "Preferred Name", "NIPD", "NISN", "NIK", "Birth Place", "Birth Date", "Gender", "Religion", "Student Status", "Address", "Kelurahan", "Kecamatan", "City", "Province", "Postal Code", "Phone", "Email", "Guardian Name", "Guardian Phone", "Attendance Device No. ID", "Device Source", "Academic Year ID", "Academic Year", "Academic Class ID", "Class",
];
const PROFILE: Record<string, string> = { "Legal Name": "full_name", "Preferred Name": "preferred_name", NIPD: "nipd", NISN: "nisn", NIK: "nik", "Birth Place": "birth_place", "Birth Date": "birth_date", Gender: "gender", Religion: "religion", "Student Status": "student_status" };
const ADDRESS: Record<string, string> = { Address: "address", Kelurahan: "kelurahan", Kecamatan: "kecamatan", City: "city_regency", Province: "province", "Postal Code": "postal_code" };
const CONTACT: Record<string, string> = { Phone: "student_phone", Email: "student_email" };
const IDENTITY_FIELDS = ["full_name", "preferred_name", "nipd", "nisn", "nik", "birth_place", "birth_date", "gender", "religion", "citizenship", "blood_type", "student_status", "admission_date", "admission_type", "previous_school"];

function rows(context: AuthContext, sql: string, params: any[] = []): Row[] { return context.database.client.query(sql).all(...params) as Row[]; }
function row(context: AuthContext, sql: string, params: any[] = []): Row | null { return (context.database.client.query(sql).get(...params) as Row | null) ?? null; }
function parsed(value: unknown): any { if (value == null || value === "") return null; if (typeof value !== "string") return value; try { return JSON.parse(value); } catch { return null; } }
function clean(value: unknown): string | null { if (value == null || value === "") return null; if (value instanceof Date) return value.toISOString().slice(0, 10); const text = String(value).trim(); return text || null; }
function stable(value: any): string { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stable(value[key])}`).join(",")}}`; return JSON.stringify(value); }
function digest(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function recordVersion(value: Row): string { return digest([value.id, value.updated_at ? String(value.updated_at).replace(" ", "T") : "", ...IDENTITY_FIELDS.map((field) => value[field] || "")].join("|")); }
function fail(set: any, status: number, detail: string | Row): Row { set.status = status; return { detail }; }
function resultResponse(bytes: Uint8Array, filename: string): Response { return new Response(bytes, { headers: { "content-type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "content-disposition": `attachment; filename="${filename}"` } }); }

function currentFields(context: AuthContext, student: Row): Row {
  const address = row(context, "SELECT * FROM student_addresses WHERE student_master_id = ?", [student.id]);
  const contact = row(context, "SELECT * FROM student_contacts WHERE student_master_id = ?", [student.id]);
  const guardian = row(context, "SELECT * FROM student_parent_guardians WHERE student_master_id = ? ORDER BY id LIMIT 1", [student.id]);
  const device = row(context, "SELECT * FROM student_device_identities WHERE student_master_id = ? AND is_active = 1 ORDER BY id DESC LIMIT 1", [student.id]);
  const enrollment = row(context, "SELECT e.*, ay.label AS academic_year FROM student_enrollments e LEFT JOIN academic_years ay ON ay.id = e.academic_year_id WHERE e.student_master_id = ? ORDER BY e.academic_year_id DESC, e.id DESC LIMIT 1", [student.id]);
  return { ...student, ...Object.fromEntries(Object.values(ADDRESS).map((field) => [field, address?.[field] ?? null])), student_phone: contact?.student_phone ?? null, student_email: contact?.student_email ?? null, guardian_name: guardian?.name ?? null, guardian_phone: guardian?.phone ?? null, device_identifier: device?.device_identifier ?? null, device_source: device?.device_source ?? "attendance_machine", academic_year_id: enrollment?.academic_year_id ?? null, academic_year: enrollment?.academic_year ?? null, academic_class_id: enrollment?.academic_class_id ?? null, class_name: enrollment?.class_name ?? null };
}

function serialize(context: AuthContext, batch: Row): Row {
  const values = rows(context, "SELECT * FROM student_import_rows WHERE batch_id = ? ORDER BY source_row", [batch.id]);
  return { id: batch.id, session_id: batch.session_id, filename: batch.filename, file_checksum: batch.file_checksum, status: batch.status, created_by: batch.created_by, created_at: batch.created_at, committed_at: batch.committed_at, preview_checksum: digest(stable(values.map((value) => ({ source_row: value.source_row, classification: value.classification, student: value.matched_student_master_id, payload: parsed(value.normalized_payload), differences: parsed(value.differences), errors: parsed(value.validation_errors) })))), summary: { total: batch.total_rows, updates: batch.update_count, unchanged: batch.unchanged_count, conflicts: batch.conflict_count, invalid: batch.invalid_count }, rows: values.map((value) => ({ id: value.id, source_row: value.source_row, classification: value.classification, student_master_id: value.matched_student_master_id, payload: parsed(value.normalized_payload), differences: parsed(value.differences), errors: parsed(value.validation_errors), selected: Boolean(value.selected_for_commit) })) };
}

async function template(context: AuthContext): Promise<Uint8Array> {
  const workbook = createWorkbook({ exportType: "student-update-template" }); const sheet = addWorksheet(workbook, "Student Data"); appendRow(sheet, HEADERS);
  for (const student of rows(context, "SELECT * FROM student_masters ORDER BY full_name, id")) {
    const current = currentFields(context, student);
    appendRow(sheet, [student.id, recordVersion(student), student.full_name, student.preferred_name, student.nipd, student.nisn, student.nik, student.birth_place, student.birth_date, student.gender, student.religion, student.student_status, current.address, current.kelurahan, current.kecamatan, current.city_regency, current.province, current.postal_code, current.student_phone, current.student_email, current.guardian_name, current.guardian_phone, current.device_identifier, current.device_source, current.academic_year_id, current.academic_year, current.academic_class_id, current.class_name]);
  }
  sheet.views = [{ state: "frozen", ySplit: 1 }]; sheet.autoFilter = { from: "A1", to: sheet.getCell(1, HEADERS.length).address }; sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } }; sheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E3A5F" } };
  const reference = addWorksheet(workbook, "Reference Values"); appendRow(reference, ["Gender", "Religion", "Student Status"]); ["male", "female", "", "Islam", "Christian", "Catholic", "Hindu", "Buddhist", "Other", "", "pending_review", "active", "inactive", "transferred", "withdrawn", "graduated", "archived"].forEach((value, index) => reference.getCell(index + 2, index < 2 ? 1 : index < 9 ? 2 : 3).value = value); reference.state = "hidden";
  const instructions = addWorksheet(workbook, "Instructions"); appendRow(instructions, ["OperatorOS Student Data Update"]); appendRow(instructions, ["Match rule", "Rows match only by OperatorOS Student UUID."]); appendRow(instructions, ["Concurrency", "Do not edit Record Version. Stale rows are blocked during preview."]); appendRow(instructions, ["Commit", "Upload creates a preview only. Select and confirm changes before commit."]); return writeXlsxWorkbook(workbook);
}

async function preview(context: AuthContext, file: File, user: Row, set: any): Promise<Row> {
  if (!file.name.toLowerCase().endsWith(".xlsx")) return fail(set, 400, "Student update file must be XLSX"); const bytes = await file.arrayBuffer(); if (!bytes.byteLength || bytes.byteLength > 25 * 1024 * 1024) return fail(set, 400, "Student update file must be between 1 byte and 25 MB");
  let workbook: ExcelWorkbook; try { workbook = await loadXlsxWorkbook(bytes); } catch { return fail(set, 400, "The uploaded file is not a readable XLSX workbook"); } const sheet = workbook.getWorksheet("Student Data"); if (!sheet) return fail(set, 400, "Workbook must contain the 'Student Data' worksheet"); if (sheet.rowCount > 10001) return fail(set, 400, "Workbook exceeds the 10,000-row limit");
  const values = (sheet.getRow(1).values as unknown[]).slice(1).map(clean); const missing = HEADERS.filter((header) => !values.includes(header)); if (missing.length) return fail(set, 400, { code: "MISSING_COLUMNS", columns: missing }); const index: Record<string, number> = Object.fromEntries(HEADERS.map((header) => [header, values.indexOf(header) + 1])); const checksum = digest(Buffer.from(bytes).toString("hex")); const sessionId = randomUUID(); const batchId = randomUUID(); const counts: Row = { UPDATE_EXISTING_MASTER: 0, NO_CHANGE: 0, CONFLICT: 0, INVALID: 0 };
  try {
    inTransaction(context.database.client, () => {
      context.database.client.run("INSERT INTO student_import_sessions (id, session_uuid, import_type, status, provenance_status, created_by, expires_at, source_filename, source_file_checksum, row_count, selected_row_count, applied_action_count, rollback_state, metadata, schema_version) VALUES (?, ?, 'STUDENT_DATA_UPDATE', 'PREVIEW_CREATED', 'PROVENANCE_FAILED', ?, datetime('now', '+24 hours'), ?, ?, 0, 0, 0, 'NOT_AVAILABLE', '{}', '1')", [sessionId, sessionId, user.username, file.name, checksum]);
      context.database.client.run("INSERT INTO student_import_batches (id, session_id, filename, file_checksum, source_sheet, status, total_rows, update_count, unchanged_count, conflict_count, invalid_count, created_by) VALUES (?, ?, ?, ?, 'student_update', 'preview', 0, 0, 0, 0, 0, ?)", [batchId, sessionId, file.name, checksum, user.username]);
      const importRows: Row[] = [];
      for (let number = 2; number <= sheet.rowCount; number++) {
        const valuesForRow = sheet.getRow(number).values as unknown[]; if (!valuesForRow.slice(1).some((value) => clean(value))) continue; const payload: Row = Object.fromEntries(HEADERS.map((header) => [header, clean(valuesForRow[index[header]!] as unknown)])); const errors: Row[] = []; const differences: Row = {}; const student = payload["OperatorOS Student UUID"] ? row(context, "SELECT * FROM student_masters WHERE id = ?", [payload["OperatorOS Student UUID"]]) : null; let classification = "INVALID";
        if (!payload["OperatorOS Student UUID"]) errors.push({ code: "MISSING_UUID", message: "OperatorOS Student UUID is required" }); else if (!student) errors.push({ code: "UNKNOWN_UUID", message: "Student UUID was not found" }); else if (payload["Record Version"] !== recordVersion(student)) { classification = "CONFLICT"; errors.push({ code: "STALE_RECORD", message: "Student changed after this workbook was exported" }); } else {
          const current = currentFields(context, student);
          for (const [header, field] of Object.entries(PROFILE)) if (current[field] !== payload[header]) differences[field] = { current: current[field] ?? null, uploaded: payload[header], action: "update_profile" };
          for (const [header, field] of Object.entries(ADDRESS)) if (current[field] !== payload[header]) differences[field] = { current: current[field] ?? null, uploaded: payload[header], action: "update_profile" };
          for (const [header, field] of Object.entries(CONTACT)) if (current[field] !== payload[header]) differences[field] = { current: current[field] ?? null, uploaded: payload[header], action: "update_profile" };
          if (current.guardian_name !== payload["Guardian Name"]) differences.guardian_name = { current: current.guardian_name, uploaded: payload["Guardian Name"], action: "update_guardian" }; if (current.guardian_phone !== payload["Guardian Phone"]) differences.guardian_phone = { current: current.guardian_phone, uploaded: payload["Guardian Phone"], action: "update_guardian" };
          if (current.device_identifier !== payload["Attendance Device No. ID"]) differences.device_identifier = { current: current.device_identifier, uploaded: payload["Attendance Device No. ID"], action: "replace_device" }; if (payload["Attendance Device No. ID"] && !/^\d+$/.test(payload["Attendance Device No. ID"])) errors.push({ code: "INVALID_DEVICE_ID", field: "Attendance Device No. ID", message: "Device ID must contain digits only" });
          if (payload.NISN && (!/^\d+$/.test(payload.NISN) || payload.NISN.length !== 10)) errors.push({ code: "INVALID_NISN", field: "NISN", message: "NISN must contain 10 digits" }); if (payload.NIK && (!/^\d+$/.test(payload.NIK) || payload.NIK.length !== 16)) errors.push({ code: "INVALID_NIK", field: "NIK", message: "NIK must contain 16 digits" }); if (!payload["Legal Name"]) errors.push({ code: "REQUIRED", field: "Legal Name", message: "Legal Name is required" });
          const yearId = payload["Academic Year ID"] && /^\d+$/.test(payload["Academic Year ID"]) ? Number(payload["Academic Year ID"]) : null; const classId = payload["Academic Class ID"] && /^\d+$/.test(payload["Academic Class ID"]) ? Number(payload["Academic Class ID"]) : null; if (classId && (!yearId || !row(context, "SELECT id FROM academic_classes WHERE id = ? AND academic_year_id = ? AND active = 1", [classId, yearId]))) errors.push({ code: "INVALID_ACADEMIC_CLASS", message: "Academic class does not belong to the selected academic year" }); if (classId && current.academic_class_id !== classId) differences.academic_class_id = { current: current.academic_class_id, uploaded: classId, action: "transfer_or_enroll" };
          if (payload.NIPD && row(context, "SELECT id FROM student_masters WHERE nipd = ? AND id != ?", [payload.NIPD, student.id])) errors.push({ code: "DUPLICATE_NIPD", message: "NIPD belongs to another student" }); if (payload.NISN && row(context, "SELECT id FROM student_masters WHERE nisn = ? AND id != ?", [payload.NISN, student.id])) errors.push({ code: "DUPLICATE_NISN", message: "NISN belongs to another student" }); if (payload.NIK && row(context, "SELECT id FROM student_masters WHERE nik = ? AND id != ?", [payload.NIK, student.id])) errors.push({ code: "DUPLICATE_NIK", message: "NIK belongs to another student" });
          classification = errors.length ? "INVALID" : Object.keys(differences).length ? "UPDATE_EXISTING_MASTER" : "NO_CHANGE";
        }
        counts[classification]++; context.database.client.run("INSERT INTO student_import_rows (batch_id, source_row, classification, matched_student_master_id, normalized_payload, differences, validation_errors, selected_for_commit) VALUES (?, ?, ?, ?, ?, ?, ?, 0)", [batchId, number, classification, student?.id ?? null, JSON.stringify(payload), JSON.stringify(differences), JSON.stringify(errors)]); importRows.push({ source_row: number, classification, student: student?.id ?? null, payload, differences, errors });
      }
      const previewChecksum = digest(stable(importRows)); context.database.client.run("UPDATE student_import_batches SET total_rows = ?, update_count = ?, unchanged_count = ?, conflict_count = ?, invalid_count = ? WHERE id = ?", [importRows.length, counts.UPDATE_EXISTING_MASTER, counts.NO_CHANGE, counts.CONFLICT, counts.INVALID, batchId]); context.database.client.run("UPDATE student_import_sessions SET status = 'PREVIEW_READY', preview_checksum = ?, row_count = ? WHERE id = ?", [previewChecksum, importRows.length, sessionId]);
    });
  } catch { return fail(set, 409, "Student update preview could not be created"); }
  return serialize(context, row(context, "SELECT * FROM student_import_batches WHERE id = ?", [batchId]) as Row);
}

function commit(context: AuthContext, batchId: string, body: Row, user: Row, set: any): Row {
  if (body.confirmation !== UPDATE_CONFIRMATION) return fail(set, 400, "Invalid confirmation token"); const batch = row(context, "SELECT * FROM student_import_batches WHERE id = ? AND source_sheet = 'student_update'", [batchId]); if (!batch) return fail(set, 404, "Student update preview not found"); if (batch.status === "committed") return { status: "committed", batch_id: batch.id, updated: batch.update_count, idempotent_replay: true }; const values = rows(context, "SELECT * FROM student_import_rows WHERE batch_id = ? ORDER BY source_row", [batchId]); const previewChecksum = digest(stable(values.map((value) => ({ source_row: value.source_row, classification: value.classification, student: value.matched_student_master_id, payload: parsed(value.normalized_payload), differences: parsed(value.differences), errors: parsed(value.validation_errors) })))); if (body.preview_checksum !== previewChecksum) return fail(set, 409, "Preview changed; upload the workbook again"); const session = row(context, "SELECT * FROM student_import_sessions WHERE id = ?", [batch.session_id]); if (!session || session.created_by !== user.username || session.status !== "PREVIEW_READY" || session.preview_checksum !== previewChecksum) return fail(set, 409, "Import session preview is stale"); const selectedIds = [...new Set(body.selected_row_ids as number[])]; const selected = values.filter((value) => selectedIds.includes(Number(value.id))); if (!selected.length || selected.length !== selectedIds.length) return fail(set, 400, "Selected rows are not part of this preview"); const blocked = selected.filter((value) => value.classification !== "UPDATE_EXISTING_MASTER"); if (blocked.length) return fail(set, 409, { code: "ROWS_NOT_COMMITTABLE", rows: blocked.map((value) => value.source_row) });
    try { let actionCount = 0; inTransaction(context.database.client, () => { for (const importRow of selected) { const payload = parsed(importRow.normalized_payload) as Row; const differences = parsed(importRow.differences) as Row; const student = row(context, "SELECT * FROM student_masters WHERE id = ?", [importRow.matched_student_master_id]); if (!student || payload["Record Version"] !== recordVersion(student)) throw new Error("STALE_RECORD"); const profileUpdates = Object.entries(PROFILE).filter(([, field]) => differences[field]).map(([, field]) => field); if (profileUpdates.length) { const assignments = profileUpdates.map((field) => `${field} = ?`).join(", "); context.database.client.run(`UPDATE student_masters SET ${assignments}, normalized_name = ?, updated_by = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?`, [...profileUpdates.map((field) => differences[field].uploaded), profileUpdates.includes("full_name") ? String(differences.full_name.uploaded).normalize("NFKC").trim().replace(/\s+/g, " ").toLowerCase() : student.normalized_name, user.username, student.id]); actionCount++; }
      for (const [header, field] of Object.entries(ADDRESS)) if (differences[field]) { const existing = row(context, "SELECT id FROM student_addresses WHERE student_master_id = ?", [student.id]); const valuesForChange = [differences[field].uploaded]; if (existing) context.database.client.run(`UPDATE student_addresses SET ${field} = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?`, [valuesForChange[0], existing.id]); else context.database.client.run(`INSERT INTO student_addresses (student_master_id, ${field}) VALUES (?, ?)`, [student.id, valuesForChange[0]]); }
      for (const [header, field] of Object.entries(CONTACT)) if (differences[field]) { const existing = row(context, "SELECT id FROM student_contacts WHERE student_master_id = ?", [student.id]); if (existing) context.database.client.run(`UPDATE student_contacts SET ${field} = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?`, [differences[field].uploaded, existing.id]); else context.database.client.run(`INSERT INTO student_contacts (student_master_id, ${field}) VALUES (?, ?)`, [student.id, differences[field].uploaded]); }
      if (differences.guardian_name || differences.guardian_phone) { const existing = row(context, "SELECT id, name FROM student_parent_guardians WHERE student_master_id = ? ORDER BY id LIMIT 1", [student.id]); if (existing) context.database.client.run("UPDATE student_parent_guardians SET name = COALESCE(?, name), phone = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?", [payload["Guardian Name"], payload["Guardian Phone"], existing.id]); else context.database.client.run("INSERT INTO student_parent_guardians (student_master_id, guardian_type, name, phone) VALUES (?, 'guardian', ?, ?)", [student.id, payload["Guardian Name"] || "Not provided", payload["Guardian Phone"]]); }
      if (differences.device_identifier) { const old = row(context, "SELECT * FROM student_device_identities WHERE student_master_id = ? AND is_active = 1 ORDER BY id DESC LIMIT 1", [student.id]); if (old) context.database.client.run("UPDATE student_device_identities SET is_active = 0, effective_to = CURRENT_DATE WHERE id = ?", [old.id]); if (payload["Attendance Device No. ID"]) { const identifier = String(payload["Attendance Device No. ID"]); if (row(context, "SELECT id FROM student_device_identities WHERE device_identifier = ? AND is_active = 1", [identifier])) throw new Error("DEVICE_ID_IN_USE"); const legacyId = Number(identifier); if (!row(context, "SELECT id FROM students WHERE id = ?", [legacyId])) context.database.client.run("INSERT INTO students (id, name) VALUES (?, ?)", [legacyId, student.full_name]); context.database.client.run("INSERT INTO student_device_identities (student_master_id, legacy_student_id, device_identifier, device_source, effective_from, is_active, created_by) VALUES (?, ?, ?, ?, CURRENT_DATE, 1, ?)", [student.id, legacyId, identifier, payload["Device Source"] || "attendance_machine", user.username]); } actionCount++; }
      if (differences.academic_class_id) { const classId = Number(differences.academic_class_id.uploaded); const yearId = Number(payload["Academic Year ID"]); const hierarchy = row(context, "SELECT c.id, c.class_name, g.jenjang_id FROM academic_classes c JOIN academic_grades g ON g.id = c.grade_id WHERE c.id = ? AND c.academic_year_id = ? AND c.active = 1", [classId, yearId]); if (!hierarchy) throw new Error("ACADEMIC_CLASS"); const mapping = row(context, "SELECT legacy_student_id FROM student_device_identities WHERE student_master_id = ? AND is_active = 1 LIMIT 1", [student.id]); const existing = row(context, "SELECT id FROM student_enrollments WHERE student_master_id = ? AND academic_year_id = ?", [student.id, yearId]); if (existing) context.database.client.run("UPDATE student_enrollments SET student_id = ?, jenjang_id = ?, academic_class_id = ?, class_name = ?, class_assigned = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?", [mapping?.legacy_student_id ?? null, hierarchy.jenjang_id, hierarchy.id, hierarchy.class_name, existing.id]); else context.database.client.run("INSERT INTO student_enrollments (student_id, student_master_id, academic_year_id, jenjang_id, academic_class_id, class_name, class_assigned, effective_from, lifecycle_state) VALUES (?, ?, ?, ?, ?, ?, 1, CURRENT_DATE, 'ACTIVE')", [mapping?.legacy_student_id ?? null, student.id, yearId, hierarchy.jenjang_id, hierarchy.id, hierarchy.class_name]); actionCount++; }
      context.database.client.run("UPDATE student_import_rows SET selected_for_commit = 1 WHERE id = ?", [importRow.id]); }
      context.database.client.run("UPDATE student_import_batches SET status = 'committed', committed_at = CURRENT_TIMESTAMP, update_count = ? WHERE id = ?", [selected.length, batch.id]); context.database.client.run("UPDATE student_import_sessions SET status = 'COMMITTED', provenance_status = 'COMPLETE_ACTION_PROVENANCE', rollback_state = 'AVAILABLE', committed_at = CURRENT_TIMESTAMP, committed_by = ?, selected_row_count = ?, applied_action_count = ? WHERE id = ?", [user.username, selected.length, actionCount, session.id]); }); return { status: "committed", batch_id: batch.id, updated: selected.length, idempotent_replay: false }; } catch (error) { return fail(set, 409, (error as Error).message === "STALE_RECORD" ? "Student changed after preview" : (error as Error).message === "DEVICE_ID_IN_USE" ? "Attendance Device ID conflicts with current data" : "Student update conflicts with current data"); }
}

async function resultWorkbook(context: AuthContext, batch: Row): Promise<Uint8Array> { const workbook = createWorkbook({ exportType: "student-update-result" }); const sheet = addWorksheet(workbook, "Validation Summary"); appendRow(sheet, ["Original Row", "Student UUID", "Name", "Status", "Proposed Action", "Result", "Error Code", "Error Message", "Suggested Resolution"]); for (const value of rows(context, "SELECT * FROM student_import_rows WHERE batch_id = ? ORDER BY source_row", [batch.id])) { const payload = parsed(value.normalized_payload) ?? {}; const differences = parsed(value.differences) ?? {}; const errors = parsed(value.validation_errors) ?? []; appendRow(sheet, [value.source_row, value.matched_student_master_id, payload["Legal Name"], value.classification, [...new Set(Object.values(differences).map((change: any) => change.action))].join(", "), Number(value.selected_for_commit) && batch.status === "committed" ? "Committed" : "Not committed", errors[0]?.code, errors[0]?.message, errors.length ? "Re-export current data and resolve the indicated row" : null]); } return writeXlsxWorkbook(workbook); }

export function studentUpdateRoutes(app: any, context: AuthContext): any {
  app.get("/api/student-masters/management/export-template", async ({ set, ...ctx }: Context) => { const user = actor(context, { set, ...ctx }, { capability: "export_student_data" }); if (!user) return { detail: "Insufficient permissions" }; return resultResponse(await template(context), "operatoros-student-update.xlsx"); });
  app.post("/api/student-masters/management/update-preview", async ({ body, set, ...ctx }: Context) => { const user = actor(context, { set, ...ctx }, { capability: "import_student_updates" }); if (!user) return { detail: "Insufficient permissions" }; return preview(context, body.file as File, user, set); }, { body: t.Object({ file: t.File() }) });
  app.post("/api/student-masters/management/update-commit/:batch_id", ({ params, body, set, ...ctx }: Context) => { const user = actor(context, { set, ...ctx }, { capability: "commit_student_updates" }); if (!user) return { detail: "Insufficient permissions" }; return commit(context, params.batch_id, body, user, set); }, { params: t.Object({ batch_id: t.String({ minLength: 1, maxLength: 36 }) }), body: t.Object({ selected_row_ids: t.Array(t.Number({ minimum: 1 }), { minItems: 1 }), confirmation: t.Literal(UPDATE_CONFIRMATION), preview_checksum: t.String({ minLength: 64, maxLength: 64 }) }) });
  app.get("/api/student-masters/management/import-history", ({ query, set, ...ctx }: Context) => { const user = actor(context, { set, ...ctx }, { capability: "view_student_audit" }); if (!user) return { detail: "Insufficient permissions" }; const page = Math.max(1, Number(query.page ?? 1)); const pageSize = Math.min(100, Math.max(1, Number(query.page_size ?? 25))); const total = Number((row(context, "SELECT COUNT(*) AS count FROM student_import_batches WHERE source_sheet = 'student_update'") as Row).count); return { items: rows(context, "SELECT * FROM student_import_batches WHERE source_sheet = 'student_update' ORDER BY created_at DESC LIMIT ? OFFSET ?", [pageSize, (page - 1) * pageSize]).map((value) => serialize(context, value)), total, page, page_size: pageSize }; }, { query: t.Object({ page: t.Optional(t.String()), page_size: t.Optional(t.String()) }) });
  app.get("/api/student-masters/management/imports/:batch_id", ({ params, set, ...ctx }: Context) => { const user = actor(context, { set, ...ctx }, { capability: "view_student_audit" }); if (!user) return { detail: "Insufficient permissions" }; const batch = row(context, "SELECT * FROM student_import_batches WHERE id = ? AND source_sheet = 'student_update'", [params.batch_id]); return batch ? serialize(context, batch) : fail(set, 404, "Student update import not found"); }, { params: t.Object({ batch_id: t.String({ minLength: 1, maxLength: 36 }) }) });
  app.get("/api/student-masters/management/imports/:batch_id/result.xlsx", async ({ params, set, ...ctx }: Context) => { const user = actor(context, { set, ...ctx }, { capability: "view_student_audit" }); if (!user) return { detail: "Insufficient permissions" }; const batch = row(context, "SELECT * FROM student_import_batches WHERE id = ? AND source_sheet = 'student_update'", [params.batch_id]); if (!batch) return fail(set, 404, "Student update import not found"); return resultResponse(await resultWorkbook(context, batch), `student-update-result-${batch.id}.xlsx`); }, { params: t.Object({ batch_id: t.String({ minLength: 1, maxLength: 36 }) }) });
  return app;
}
