import { useState } from "react";
import { CheckCircle2, Download, FileSpreadsheet, Users } from "lucide-react";
import AttendanceUpload from "./Upload";
import { useRosterCommit, useRosterPreview, useStudentTemplateExport, useStudentUpdateCommit, useStudentUpdatePreview } from "../hooks/useStudentQueries";
import { PageHeader } from "../components/common/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Alert, AlertDescription, AlertTitle } from "../components/ui/alert";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { DataTable, DataTableBody, DataTableCell, DataTableContainer, DataTableHead, DataTableHeader, DataTableRow } from "../components/common/data-table";
import { buildApiUrl } from "../lib/api/client";

const today = new Date().toISOString().slice(0, 10);
function saveBlob(blob: Blob, filename: string) { const href = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = href; anchor.download = filename; anchor.click(); URL.revokeObjectURL(href); }

function RosterImportPanel() {
  const preview = useRosterPreview(); const commit = useRosterCommit();
  const [file, setFile] = useState<File | null>(null); const [owner, setOwner] = useState(""); const [received, setReceived] = useState(today); const [selected, setSelected] = useState<number[]>([]);
  const runPreview = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return; const result = await preview.mutateAsync({ file, owner, received }); setSelected(result.rows.filter((row: any) => ["CREATE_ENROLLMENT", "CREATE_NEW_MASTER"].includes(row.classification)).map((row: any) => row.preview_row_id)); };
  const runCommit = () => commit.mutate({ preview_id: preview.data.preview_id, selected_row_ids: selected, confirmation: "COMMIT_ACADEMIC_ROSTER", preview_checksum: preview.data.preview_checksum });
  return <div className="space-y-5"><Card><CardHeader><CardTitle>Student Roster</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Create canonical students or enroll confidently matched students. Uploading never commits automatically.</p><a className="inline-flex min-h-10 items-center gap-2 rounded-md border border-border px-4 py-2 text-sm font-bold hover:bg-surface-muted" href={buildApiUrl("/api/student-enrollments/roster-template")} download><Download className="size-4" />Download roster template</a><form className="grid gap-4 sm:grid-cols-3" onSubmit={runPreview}><div className="sm:col-span-3"><Label htmlFor="roster-file">Roster workbook (.xlsx)</Label><Input id="roster-file" type="file" accept=".xlsx" required onChange={(event) => setFile(event.target.files?.[0] || null)} /></div><div><Label htmlFor="roster-owner">Source owner</Label><Input id="roster-owner" required minLength={2} value={owner} onChange={(event) => setOwner(event.target.value)} /></div><div><Label htmlFor="roster-received">Date received</Label><Input id="roster-received" type="date" required value={received} onChange={(event) => setReceived(event.target.value)} /></div><div className="flex items-end"><Button type="submit" disabled={preview.isPending || !file}>{preview.isPending ? "Validating roster…" : "Preview roster"}</Button></div></form>{preview.error && <Alert variant="danger"><AlertTitle>Roster preview failed</AlertTitle><AlertDescription>{preview.error.message}</AlertDescription></Alert>}</CardContent></Card>
    {preview.data && <Card><CardHeader><CardTitle>Roster preview</CardTitle></CardHeader><CardContent className="space-y-4"><div role="status" aria-live="polite" className="flex flex-wrap gap-2"><Badge>{preview.data.summary.total} rows</Badge><Badge variant="success">{preview.data.summary.create_new_master || 0} new students</Badge><Badge variant="information">{preview.data.summary.create_enrollment || 0} enrollments</Badge><Badge variant="warning">{(preview.data.summary.invalid || 0) + (preview.data.summary.possible_duplicate || 0)} need attention</Badge></div><DataTableContainer><DataTable><DataTableHeader><DataTableRow><DataTableHead>Select</DataTableHead><DataTableHead>Row</DataTableHead><DataTableHead>Student</DataTableHead><DataTableHead>Action</DataTableHead><DataTableHead>Validation</DataTableHead></DataTableRow></DataTableHeader><DataTableBody>{preview.data.rows.map((row: any) => { const allowed = ["CREATE_ENROLLMENT", "CREATE_NEW_MASTER"].includes(row.classification); return <DataTableRow key={row.preview_row_id}><DataTableCell><input aria-label={`Select roster row ${row.source_row}`} type="checkbox" disabled={!allowed || commit.isPending} checked={selected.includes(row.preview_row_id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, row.preview_row_id] : current.filter((id) => id !== row.preview_row_id))} /></DataTableCell><DataTableCell>{row.source_row}</DataTableCell><DataTableCell>{row.payload.student_name}</DataTableCell><DataTableCell><Badge variant={allowed ? "success" : "warning"}>{row.classification.replaceAll("_", " ")}</Badge></DataTableCell><DataTableCell>{row.errors?.join("; ") || "Ready"}</DataTableCell></DataTableRow>; })}</DataTableBody></DataTable></DataTableContainer><div className="flex flex-wrap items-center gap-3"><Button onClick={runCommit} disabled={!selected.length || commit.isPending}>{commit.isPending ? "Committing selected rows…" : `Commit ${selected.length} selected row(s)`}</Button><p className="text-xs text-muted-foreground">Confirmation is bound to this preview checksum.</p></div>{commit.isSuccess && <Alert variant="success"><AlertTitle>Roster committed</AlertTitle><AlertDescription>{(commit.data as any).students_created} canonical student(s) created and {(commit.data as any).created} enrollment(s) created.</AlertDescription></Alert>}{commit.error && <Alert variant="danger"><AlertTitle>Roster was not committed</AlertTitle><AlertDescription>{commit.error.message}</AlertDescription></Alert>}</CardContent></Card>}
  </div>;
}

function StudentUpdatePanel() {
  const exporter = useStudentTemplateExport(); const preview = useStudentUpdatePreview(); const commit = useStudentUpdateCommit();
  const [file, setFile] = useState<File | null>(null); const [selected, setSelected] = useState<number[]>([]);
  const exportFile = async () => saveBlob(await exporter.mutateAsync(), "operatoros-student-update.xlsx");
  const runPreview = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return; const result = await preview.mutateAsync(file); setSelected(result.rows.filter((row: any) => row.classification === "UPDATE_EXISTING_MASTER").map((row: any) => row.id)); };
  const runCommit = () => commit.mutate({ batchId: preview.data.id, payload: { selected_row_ids: selected, confirmation: "COMMIT_STUDENT_DATA_UPDATE", preview_checksum: preview.data.preview_checksum } });
  return <div className="space-y-5"><Card><CardHeader><CardTitle>Student Data Update</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Export current database rows, edit approved fields, then upload the workbook for field-level comparison and stale-version checks.</p><Button variant="outline" onClick={exportFile} disabled={exporter.isPending}><Download className="size-4" />{exporter.isPending ? "Generating template…" : "Export Student Update Template"}</Button><form className="flex flex-col gap-4 sm:flex-row sm:items-end" onSubmit={runPreview}><div className="flex-1"><Label htmlFor="student-update-file">Edited student update workbook</Label><Input id="student-update-file" type="file" accept=".xlsx" required onChange={(event) => setFile(event.target.files?.[0] || null)} /></div><Button type="submit" disabled={preview.isPending || !file}>{preview.isPending ? "Comparing changes…" : "Preview changes"}</Button></form>{preview.error && <Alert variant="danger"><AlertTitle>Update preview failed</AlertTitle><AlertDescription>{preview.error.message}</AlertDescription></Alert>}</CardContent></Card>
    {preview.data && <Card><CardHeader><CardTitle>Detected student changes</CardTitle></CardHeader><CardContent className="space-y-4"><div role="status" aria-live="polite" className="flex flex-wrap gap-2"><Badge>{preview.data.summary.total} rows</Badge><Badge variant="information">{preview.data.summary.updates} updates</Badge><Badge variant="secondary">{preview.data.summary.unchanged} unchanged</Badge><Badge variant="warning">{preview.data.summary.conflicts} stale conflicts</Badge><Badge variant="danger">{preview.data.summary.invalid} invalid</Badge></div><DataTableContainer><DataTable><DataTableHeader><DataTableRow><DataTableHead>Select</DataTableHead><DataTableHead>Row</DataTableHead><DataTableHead>Student</DataTableHead><DataTableHead>Status</DataTableHead><DataTableHead>Field comparisons</DataTableHead></DataTableRow></DataTableHeader><DataTableBody>{preview.data.rows.map((row: any) => <DataTableRow key={row.id}><DataTableCell><input aria-label={`Select student update row ${row.source_row}`} type="checkbox" disabled={row.classification !== "UPDATE_EXISTING_MASTER" || commit.isPending} checked={selected.includes(row.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, row.id] : current.filter((id) => id !== row.id))} /></DataTableCell><DataTableCell>{row.source_row}</DataTableCell><DataTableCell>{row.payload["Legal Name"]}</DataTableCell><DataTableCell><Badge variant={row.classification === "UPDATE_EXISTING_MASTER" ? "success" : row.classification === "NO_CHANGE" ? "secondary" : "warning"}>{row.classification.replaceAll("_", " ")}</Badge></DataTableCell><DataTableCell><ul className="space-y-1">{Object.entries(row.differences || {}).map(([field, change]: any) => <li key={field}><span className="font-bold">{field.replaceAll("_", " ")}:</span> {String(change.current || "empty")} → {String(change.uploaded || "empty")}</li>)}{row.errors?.map((error: any) => <li key={`${error.code}-${error.field || "row"}`} className="text-danger">{error.message}</li>)}</ul></DataTableCell></DataTableRow>)}</DataTableBody></DataTable></DataTableContainer><div className="flex flex-wrap items-center gap-3"><Button onClick={runCommit} disabled={!selected.length || commit.isPending}>{commit.isPending ? "Applying selected updates…" : `Commit ${selected.length} selected update(s)`}</Button><a className="text-sm font-bold text-brand hover:underline" href={buildApiUrl(`/api/student-masters/management/imports/${preview.data.id}/result.xlsx`)} download>Download validation result</a></div>{commit.isSuccess && <Alert variant="success"><AlertTitle>Student updates committed</AlertTitle><AlertDescription>{(commit.data as any).updated} row(s) updated transactionally.</AlertDescription></Alert>}{commit.error && <Alert variant="danger"><AlertTitle>Updates were not committed</AlertTitle><AlertDescription>{commit.error.message}</AlertDescription></Alert>}</CardContent></Card>}
  </div>;
}

export default function UploadCenter() {
  return <div className="space-y-6"><PageHeader eyebrow="Guarded imports" title="Data Import Center" description="Choose the data type first. Each student workflow validates, previews, confirms, and records its result separately." /><Tabs defaultValue="attendance"><TabsList className="grid h-auto w-full grid-cols-1 sm:grid-cols-3"><TabsTrigger value="attendance"><FileSpreadsheet className="mr-2 inline size-4" />Attendance Data</TabsTrigger><TabsTrigger value="roster"><Users className="mr-2 inline size-4" />Student Roster</TabsTrigger><TabsTrigger value="student-update"><CheckCircle2 className="mr-2 inline size-4" />Student Data Update</TabsTrigger></TabsList><TabsContent value="attendance"><AttendanceUpload embedded /></TabsContent><TabsContent value="roster"><RosterImportPanel /></TabsContent><TabsContent value="student-update"><StudentUpdatePanel /></TabsContent></Tabs></div>;
}
