import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Edit, Link2, MoveRight, UserRound } from "lucide-react";
import { useAddStudentGuardian, useCreateEnrollment, useDeleteStudentGuardian, useEndEnrollment, useLegacyLinkStatus, useLinkLegacyStudent, useReassignDevice, useReplaceDevice, useRetireDevice, useStudent, useStudentEnrollments, useStudentHistory, useTransferEnrollment, useUpdateStudent, useUpdateStudentDocuments, useUpdateStudentGuardian, useUpdateStudentHealth } from "../hooks/useStudentQueries";
import { PageHeader } from "../components/common/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { NativeSelect } from "../components/ui/native-select";
import { Alert, AlertDescription, AlertTitle } from "../components/ui/alert";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "../components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { ErrorState, LoadingState } from "../components/common/state-message";
import { useAuth } from "../context/AuthContext";

const today = new Date().toISOString().slice(0, 10);
const identityFields = ["full_name", "preferred_name", "nipd", "nisn", "nik", "birth_place", "birth_date", "gender", "religion", "citizenship", "blood_type", "student_status", "admission_date", "admission_type", "previous_school"];

function DefinitionList({ values }: { values: Record<string, unknown> }) {
  return <dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(values).map(([key, value]) => <div key={key}><dt className="text-xs font-black uppercase tracking-wide text-muted-foreground">{key.replaceAll("_", " ")}</dt><dd className="mt-1 break-words text-sm text-foreground">{String(value || "Not provided")}</dd></div>)}</dl>;
}

function ProfileEditDialog({ id, profile, open, onOpenChange }: any) {
  const update = useUpdateStudent(id);
  const [identity, setIdentity] = useState<Record<string, any>>({});
  const [contact, setContact] = useState<Record<string, any>>({});
  useEffect(() => { if (open) { setIdentity({ ...profile.identity }); setContact({ ...profile.contact }); } }, [open, profile]);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    await update.mutateAsync({ record_version: profile.record_version, identity, contact, guardians: profile.guardians, reason: "Updated from Student Profile" });
    onOpenChange(false);
  };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Edit student profile</DialogTitle><DialogDescription>Canonical UUID and historical records cannot be changed here. Stale forms are rejected.</DialogDescription></DialogHeader>
    {update.error && <Alert variant="danger"><AlertTitle>Profile was not saved</AlertTitle><AlertDescription>{update.error.message}</AlertDescription></Alert>}
    <form id="profile-edit-form" className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={submit}>
      {identityFields.map((field) => field === "student_status" ? <div key={field}><Label htmlFor={`edit-${field}`}>Student status</Label><NativeSelect id={`edit-${field}`} value={identity[field] || "active"} onChange={(event) => setIdentity((current) => ({ ...current, [field]: event.target.value }))}><option value="active">Active</option><option value="pending_review">Pending review</option><option value="inactive">Inactive</option><option value="transferred">Transferred</option><option value="withdrawn">Withdrawn</option><option value="graduated">Graduated</option><option value="archived">Archived</option></NativeSelect></div> : <div key={field}><Label htmlFor={`edit-${field}`}>{field.replaceAll("_", " ")}</Label><Input id={`edit-${field}`} required={field === "full_name"} type={field.includes("date") ? "date" : "text"} value={identity[field] || ""} onChange={(event) => setIdentity((current) => ({ ...current, [field]: event.target.value || null }))} /></div>)}
      {["address", "kelurahan", "kecamatan", "city_regency", "province", "postal_code", "student_phone", "student_email"].map((field) => <div key={field}><Label htmlFor={`edit-${field}`}>{field.replaceAll("_", " ")}</Label><Input id={`edit-${field}`} type={field === "student_email" ? "email" : "text"} value={contact[field] || ""} onChange={(event) => setContact((current) => ({ ...current, [field]: event.target.value || null }))} /></div>)}
    </form><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)} disabled={update.isPending}>Cancel</Button><Button type="submit" form="profile-edit-form" disabled={update.isPending}>{update.isPending ? "Saving profile…" : "Save profile"}</Button></DialogFooter>
  </DialogContent></Dialog>;
}

function GuardianManager({ id, guardians }: { id: string; guardians: Array<Record<string, any>> }) {
  const add = useAddStudentGuardian(id); const update = useUpdateStudentGuardian(id); const remove = useDeleteStudentGuardian(id);
  const empty = { guardian_type: "guardian", name: "", phone: "", email: "" };
  const [values, setValues] = useState(empty); const [editingId, setEditingId] = useState<number | null>(null);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (editingId) await update.mutateAsync({ guardianId: editingId, payload: values }); else await add.mutateAsync(values); setValues(empty); setEditingId(null); };
  const pending = add.isPending || update.isPending || remove.isPending;
  return <div className="space-y-4"><div className="space-y-3">{guardians.map((guardian) => <div key={String(guardian.id)} className="flex flex-wrap items-start justify-between gap-3 rounded-xl border border-border p-4"><DefinitionList values={guardian} /><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => { setEditingId(Number(guardian.id)); setValues({ guardian_type: String(guardian.guardian_type || "guardian"), name: String(guardian.name || ""), phone: String(guardian.phone || ""), email: String(guardian.email || "") }); }}>Edit</Button><Button variant="danger" size="sm" disabled={pending} onClick={() => { if (window.confirm("Remove this guardian?")) void remove.mutateAsync(Number(guardian.id)); }}>Remove</Button></div></div>)}</div><form className="grid gap-3 rounded-xl border border-dashed border-border p-4 sm:grid-cols-4" onSubmit={save}><div><Label htmlFor="guardian-type">Relationship</Label><NativeSelect id="guardian-type" value={values.guardian_type} onChange={(event) => setValues((current) => ({ ...current, guardian_type: event.target.value }))}><option value="father">Father</option><option value="mother">Mother</option><option value="guardian">Guardian</option></NativeSelect></div><div><Label htmlFor="guardian-name">Name</Label><Input id="guardian-name" required value={values.name} onChange={(event) => setValues((current) => ({ ...current, name: event.target.value }))} /></div><div><Label htmlFor="guardian-phone">Phone</Label><Input id="guardian-phone" value={values.phone} onChange={(event) => setValues((current) => ({ ...current, phone: event.target.value }))} /></div><div><Label htmlFor="guardian-email">Email</Label><Input id="guardian-email" type="email" value={values.email} onChange={(event) => setValues((current) => ({ ...current, email: event.target.value }))} /></div><div className="sm:col-span-4 flex gap-2"><Button type="submit" disabled={pending}>{editingId ? "Save guardian" : "Add guardian"}</Button>{editingId && <Button type="button" variant="outline" onClick={() => { setEditingId(null); setValues(empty); }}>Cancel</Button>}</div></form></div>;
}

function SensitiveProfileEditor({ id, profile }: { id: string; profile: any }) {
  const saveHealth = useUpdateStudentHealth(id); const saveDocuments = useUpdateStudentDocuments(id);
  const [health, setHealth] = useState({ allergy: profile.health?.allergy || "", medical_condition: profile.health?.medical_condition || "", special_needs: profile.health?.special_needs || "" });
  const [documents, setDocuments] = useState<Record<string, boolean>>({ ...(profile.document_status || {}) });
  const documentFields = ["family_card_received", "birth_certificate_received", "parent_id_received", "school_agreement_received", "publication_consent_received"];
  return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Health profile</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={async (event) => { event.preventDefault(); await saveHealth.mutateAsync(health); }}><div><Label htmlFor="health-allergy">Allergies</Label><Input id="health-allergy" value={health.allergy} onChange={(event) => setHealth((current) => ({ ...current, allergy: event.target.value }))} /></div><div><Label htmlFor="health-medical">Medical notes</Label><Input id="health-medical" value={health.medical_condition} onChange={(event) => setHealth((current) => ({ ...current, medical_condition: event.target.value }))} /></div><div><Label htmlFor="health-needs">Special needs</Label><Input id="health-needs" value={health.special_needs} onChange={(event) => setHealth((current) => ({ ...current, special_needs: event.target.value }))} /></div><Button type="submit" disabled={saveHealth.isPending}>{saveHealth.isPending ? "Saving…" : "Save health profile"}</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Document status</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={async (event) => { event.preventDefault(); await saveDocuments.mutateAsync(documents); }}><div className="grid gap-2">{documentFields.map((field) => <label key={field} className="flex items-center justify-between gap-3 rounded-lg border border-border p-3 text-sm"><span>{field.replaceAll("_", " ")}</span><NativeSelect aria-label={field} value={documents[field] ? "received" : "missing"} onChange={(event) => setDocuments((current) => ({ ...current, [field]: event.target.value === "received" }))}><option value="received">Received</option><option value="missing">Missing</option></NativeSelect></label>)}</div><Button type="submit" disabled={saveDocuments.isPending}>{saveDocuments.isPending ? "Saving…" : "Save document status"}</Button></form></CardContent></Card></div>;
}

function DeviceDialog({ id, open, onOpenChange }: { id: string; open: boolean; onOpenChange: (open: boolean) => void }) {
  const replace = useReplaceDevice(id); const reassign = useReassignDevice(id);
  const [deviceId, setDeviceId] = useState(""); const [effective, setEffective] = useState(today); const [reason, setReason] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await replace.mutateAsync({ device_identifier: deviceId, device_source: "attendance_machine", effective_from: effective, reason, confirmation: "REPLACE_ATTENDANCE_DEVICE_ID" }); onOpenChange(false); };
  const detail = (replace.error as any)?.data?.detail;
  const conflictStudentId = detail?.code === "DEVICE_ID_IN_USE" ? detail.student_master_id : null;
  const guardedReassign = async () => { await reassign.mutateAsync({ device_identifier: deviceId, device_source: "attendance_machine", effective_from: effective, reason, previous_student_master_id: conflictStudentId, confirmation: "REASSIGN_ATTENDANCE_DEVICE_ID" }); onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Assign or replace Attendance Device ID</DialogTitle><DialogDescription>The previous mapping is retired and retained. Historical attendance is not rewritten.</DialogDescription></DialogHeader>{replace.error && <Alert variant="danger"><AlertTitle>{conflictStudentId ? "Attendance Device ID already in use" : "Device ID was not changed"}</AlertTitle><AlertDescription>{conflictStudentId ? <>This active ID belongs to another canonical student. <Link className="font-bold underline" to={`/students/${conflictStudentId}`}>Open linked student</Link> before reassignment.</> : replace.error.message}</AlertDescription></Alert>}<form id="device-form" className="mt-5 space-y-4" onSubmit={submit}><div><Label htmlFor="profile-device-id">New Attendance Device ID</Label><Input id="profile-device-id" inputMode="numeric" required value={deviceId} onChange={(event) => setDeviceId(event.target.value)} /></div><div><Label htmlFor="profile-device-date">Effective from</Label><Input id="profile-device-date" type="date" required value={effective} onChange={(event) => setEffective(event.target.value)} /></div><div><Label htmlFor="profile-device-reason">Reason</Label><Input id="profile-device-reason" required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></div></form><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>{conflictStudentId ? <Button variant="danger" onClick={guardedReassign} disabled={reassign.isPending || reason.length < 3}>{reassign.isPending ? "Reassigning Device ID…" : "Confirm guarded reassignment"}</Button> : <Button type="submit" form="device-form" disabled={replace.isPending}>{replace.isPending ? "Updating device…" : "Confirm device change"}</Button>}</DialogFooter></DialogContent></Dialog>;
}

function EnrollmentDialog({ studentId, current, open, onOpenChange }: any) {
  const create = useCreateEnrollment(studentId); const transfer = useTransferEnrollment(studentId);
  const [yearId, setYearId] = useState(""); const [classId, setClassId] = useState(""); const [effective, setEffective] = useState(today); const [reason, setReason] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (current) await transfer.mutateAsync({ id: current.id, payload: { target_class_id: Number(classId), effective_date: effective, reason, confirmation: "TRANSFER_STUDENT_ENROLLMENT" } }); else await create.mutateAsync({ academic_year_id: Number(yearId), academic_class_id: Number(classId), effective_from: effective }); onOpenChange(false); };
  const pending = create.isPending || transfer.isPending; const error = create.error || transfer.error;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{current ? "Transfer academic class" : "Create academic enrollment"}</DialogTitle><DialogDescription>{current ? "The previous class period remains in enrollment history." : "Academic enrollment can be created before an Attendance Device ID is linked."}</DialogDescription></DialogHeader>{error && <Alert variant="danger"><AlertTitle>Enrollment was not changed</AlertTitle><AlertDescription>{error.message}</AlertDescription></Alert>}<form id="enrollment-form" className="mt-5 space-y-4" onSubmit={submit}>{!current && <div><Label htmlFor="profile-year-id">Academic year ID</Label><Input id="profile-year-id" type="number" min="1" required value={yearId} onChange={(event) => setYearId(event.target.value)} /></div>}<div><Label htmlFor="profile-class-id">Target academic class ID</Label><Input id="profile-class-id" type="number" min="1" required value={classId} onChange={(event) => setClassId(event.target.value)} /></div><div><Label htmlFor="profile-transfer-date">Effective date</Label><Input id="profile-transfer-date" type="date" required value={effective} onChange={(event) => setEffective(event.target.value)} /></div>{current && <div><Label htmlFor="profile-transfer-reason">Transfer reason</Label><Input id="profile-transfer-reason" required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></div>}</form><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" form="enrollment-form" disabled={pending}>{pending ? "Saving enrollment…" : current ? "Confirm transfer" : "Create enrollment"}</Button></DialogFooter></DialogContent></Dialog>;
}

function RetireDeviceDialog({ studentId, device, open, onOpenChange }: any) {
  const retire = useRetireDevice(studentId); const [effective, setEffective] = useState(today); const [reason, setReason] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await retire.mutateAsync({ identityId: device.id, payload: { effective_to: effective, reason, confirmation: "RETIRE_ATTENDANCE_DEVICE_ID" } }); onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Retire Attendance Device ID</DialogTitle><DialogDescription>Retiring {device?.device_identifier} prevents future matching through this mapping. Historical attendance remains intact.</DialogDescription></DialogHeader><form id="retire-device-form" className="mt-5 space-y-4" onSubmit={submit}><div><Label htmlFor="retire-device-date">Effective to</Label><Input id="retire-device-date" type="date" required value={effective} onChange={(event) => setEffective(event.target.value)} /></div><div><Label htmlFor="retire-device-reason">Reason</Label><Input id="retire-device-reason" required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></div></form><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="danger" type="submit" form="retire-device-form" disabled={retire.isPending}>{retire.isPending ? "Retiring Device ID…" : "Confirm retirement"}</Button></DialogFooter></DialogContent></Dialog>;
}

function EndEnrollmentDialog({ studentId, enrollment, open, onOpenChange }: any) {
  const end = useEndEnrollment(studentId); const [effective, setEffective] = useState(today); const [reason, setReason] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await end.mutateAsync({ id: enrollment.id, payload: { effective_date: effective, reason, confirmation: "END_STUDENT_ENROLLMENT" } }); onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent role="alertdialog" showClose={false}><DialogHeader><DialogTitle>End academic enrollment?</DialogTitle><DialogDescription>This closes the current enrollment and class-history period. It does not delete the student or academic history.</DialogDescription></DialogHeader><form id="end-enrollment-form" className="mt-5 space-y-4" onSubmit={submit}><div><Label htmlFor="end-enrollment-date">Effective date</Label><Input id="end-enrollment-date" type="date" required value={effective} onChange={(event) => setEffective(event.target.value)} /></div><div><Label htmlFor="end-enrollment-reason">Reason</Label><Input id="end-enrollment-reason" required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></div></form><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button variant="danger" type="submit" form="end-enrollment-form" disabled={end.isPending}>{end.isPending ? "Ending enrollment…" : "Confirm end enrollment"}</Button></DialogFooter></DialogContent></Dialog>;
}

function LegacyLinkDialog({ id, status, open, onOpenChange }: { id: string; status: any; open: boolean; onOpenChange: (open: boolean) => void }) {
  const link = useLinkLegacyStudent(id);
  const [legacyId, setLegacyId] = useState("");
  const [reason, setReason] = useState("");
  const candidates = status?.candidates || [];
  useEffect(() => {
    if (open) setLegacyId(candidates[0]?.legacy_student_id ? String(candidates[0].legacy_student_id) : "");
  }, [open, status]);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    await link.mutateAsync({ legacy_student_id: Number(legacyId), reason, confirmation: "LINK_LEGACY_STUDENT" });
    onOpenChange(false);
  };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Review attendance identity link</DialogTitle><DialogDescription>Link one existing legacy student only after confirming the candidate. Attendance history and device identifiers are never rewritten.</DialogDescription></DialogHeader>{link.error && <Alert variant="danger"><AlertTitle>Legacy link was not changed</AlertTitle><AlertDescription>{link.error.message}</AlertDescription></Alert>}<form id="legacy-link-form" className="mt-5 space-y-4" onSubmit={submit}><div><Label htmlFor="legacy-link-candidate">Legacy candidate</Label><NativeSelect id="legacy-link-candidate" required value={legacyId} onChange={(event) => setLegacyId(event.target.value)}><option value="">Select a reviewed candidate</option>{candidates.map((candidate: any) => <option key={candidate.legacy_student_id} value={candidate.legacy_student_id}>{candidate.name} · {candidate.jenjang || "Unknown Jenjang"} · {candidate.class_name || "Unassigned"} · {candidate.attendance_count} attendance records</option>)}</NativeSelect></div><div><Label htmlFor="legacy-link-reason">Review reason</Label><Input id="legacy-link-reason" required minLength={3} value={reason} onChange={(event) => setReason(event.target.value)} /></div></form><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" form="legacy-link-form" disabled={link.isPending || !legacyId || reason.length < 3}>{link.isPending ? "Linking…" : "Confirm reviewed link"}</Button></DialogFooter></DialogContent></Dialog>;
}

export default function CanonicalStudentProfile() {
  const { id = "" } = useParams(); const student = useStudent(id); const legacyLink = useLegacyLinkStatus(id); const history = useStudentHistory(id); const enrollmentHistory = useStudentEnrollments(id);
  const { can } = useAuth();
  const [editOpen, setEditOpen] = useState(false); const [deviceOpen, setDeviceOpen] = useState(false); const [enrollmentOpen, setEnrollmentOpen] = useState(false); const [retireOpen, setRetireOpen] = useState(false); const [endOpen, setEndOpen] = useState(false); const [legacyLinkOpen, setLegacyLinkOpen] = useState(false);
  if (student.isPending) return <LoadingState title="Loading Student Profile" />;
  if (student.isError || !student.data) return <ErrorState title="Student Profile could not be loaded" description={student.error?.message} />;
  const profile = student.data; const activeEnrollment = profile.enrollments.find((item) => item.active); const activeDevice = profile.device_identities.find((item) => item.is_active); const attendanceIdentity = legacyLink.data || profile.attendance_identity || { status: "NOT_LINKED", candidates: [] };
  const flags = [!profile.identity.nisn && "Missing NISN", !profile.identity.nik && "Missing NIK", !profile.identity.birth_date && "Missing birth date", !profile.device_identities.some((item) => item.is_active) && "No active device identity", !activeEnrollment && "No current enrollment"].filter(Boolean);
  return <div className="space-y-6"><Link to="/students" className="inline-flex items-center gap-2 text-sm font-bold text-brand hover:underline"><ArrowLeft className="size-4" />Back to Student Management</Link><PageHeader eyebrow="Student Profile" title={profile.identity.full_name || "Student"} description="Canonical identity, academic enrollment, attendance device history, and audited changes." actions={<><Button variant="outline" onClick={() => setEditOpen(true)}><Edit className="size-4" />Edit profile</Button><Button variant="outline" onClick={() => setDeviceOpen(true)}><Link2 className="size-4" />Manage Device ID</Button><Button onClick={() => setEnrollmentOpen(true)}><MoveRight className="size-4" />{activeEnrollment ? "Transfer class" : "Create enrollment"}</Button></>} />
    <Tabs defaultValue="overview"><TabsList className="flex max-w-full justify-start overflow-x-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="personal">Personal Data</TabsTrigger><TabsTrigger value="contact">Contact & Guardians</TabsTrigger><TabsTrigger value="enrollment">Academic Enrollment</TabsTrigger><TabsTrigger value="device">Attendance Device</TabsTrigger><TabsTrigger value="quality">Data Quality</TabsTrigger><TabsTrigger value="history">Change History</TabsTrigger></TabsList>
      <TabsContent value="overview" className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Current student context</CardTitle></CardHeader><CardContent><DefinitionList values={{ canonical_uuid: profile.id, preferred_name: profile.identity.preferred_name, age_years: profile.age_years, status: profile.identity.student_status, academic_year: activeEnrollment?.academic_year, jenjang: activeEnrollment?.jenjang, programme: activeEnrollment?.program, grade: activeEnrollment?.grade, current_class: activeEnrollment?.class_name, attendance_device_id: profile.device_identities.find((item) => item.is_active)?.device_identifier }} /></CardContent></Card><Card><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>Attendance identity</CardTitle>{can("resolve_student_duplicates") && attendanceIdentity.status !== "LINKED" && <Button size="sm" variant="outline" onClick={() => setLegacyLinkOpen(true)}>Review / link</Button>}</div></CardHeader><CardContent className="space-y-3"><Badge variant={attendanceIdentity.status === "LINKED" ? "success" : attendanceIdentity.status === "REVIEW_REQUIRED" ? "warning" : "secondary"}>{attendanceIdentity.status === "LINKED" ? "Linked" : attendanceIdentity.status === "REVIEW_REQUIRED" ? "Review Required" : "Not Linked"}</Badge><p className="text-sm text-muted-foreground">{attendanceIdentity.status === "LINKED" ? "Historical attendance remains associated with the linked legacy identity." : attendanceIdentity.status === "REVIEW_REQUIRED" ? `${attendanceIdentity.candidates?.length || 0} candidate(s) require administrator review.` : "No legacy attendance identity is linked."}</p></CardContent></Card><Card><CardHeader><CardTitle>Profile health</CardTitle></CardHeader><CardContent>{flags.length ? <ul className="space-y-2">{flags.map((flag) => <li key={String(flag)}><Badge variant="warning">{flag}</Badge></li>)}</ul> : <Badge variant="success">No quality warnings</Badge>}</CardContent></Card><Card><CardHeader><CardTitle>Attendance Summary</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Attendance remains attached to historical device identities. Open attendance reports for detailed analytics.</p></CardContent></Card><Card><CardHeader><CardTitle>Academic Summary</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Academic records remain separate from enrollment and canonical identity.</p></CardContent></Card></TabsContent>
      <TabsContent value="personal"><Card><CardHeader><CardTitle>Personal data</CardTitle></CardHeader><CardContent><DefinitionList values={profile.identity} /></CardContent></Card></TabsContent>
      <TabsContent value="contact" className="space-y-4"><Card><CardHeader><CardTitle>Contact and address</CardTitle></CardHeader><CardContent><DefinitionList values={profile.contact} /></CardContent></Card><Card><CardHeader><CardTitle>Parents and guardians</CardTitle></CardHeader><CardContent><GuardianManager id={id} guardians={profile.guardians} /></CardContent></Card><SensitiveProfileEditor id={id} profile={profile} /></TabsContent>
      <TabsContent value="enrollment"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle>Academic enrollment history</CardTitle>{activeEnrollment && <Button variant="danger" size="sm" onClick={() => setEndOpen(true)}>End current enrollment</Button>}</div></CardHeader><CardContent className="space-y-4">{enrollmentHistory.isPending ? <LoadingState title="Loading enrollment history" /> : (enrollmentHistory.data || []).map((item: any) => <article key={item.id} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-black">{item.class_name || "Unassigned class"}</h3><Badge variant={item.active ? "success" : "secondary"}>{item.active ? "Current" : "Historical"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.effective_from || "Unknown start"} – {item.effective_to || "Current"}</p>{item.class_history?.length > 0 && <ol className="mt-3 space-y-1 text-sm">{item.class_history.map((entry: any) => <li key={entry.id}>{entry.class_name}: {entry.effective_from} – {entry.effective_to || "Current"}</li>)}</ol>}</article>)}</CardContent></Card></TabsContent>
      <TabsContent value="device"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle>Attendance Device ID history</CardTitle>{activeDevice && <Button variant="danger" size="sm" onClick={() => setRetireOpen(true)}>Retire active Device ID</Button>}</div></CardHeader><CardContent className="space-y-3">{profile.device_identities.length ? profile.device_identities.map((device) => <div key={device.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-4"><div><p className="font-mono font-black">{device.device_identifier}</p><p className="text-xs text-muted-foreground">{device.device_source} · {device.effective_from} – {device.effective_to || "Current"}</p></div><Badge variant={device.is_active ? "success" : "secondary"}>{device.is_active ? "Active" : "Retired"}</Badge></div>) : <p className="text-sm text-muted-foreground">No attendance device identity linked.</p>}</CardContent></Card></TabsContent>
      <TabsContent value="quality"><Card><CardHeader><CardTitle>Data quality</CardTitle></CardHeader><CardContent>{flags.length ? <ul className="space-y-2">{flags.map((flag) => <li key={String(flag)} className="flex items-center gap-2"><UserRound className="size-4 text-amber-600" aria-hidden="true" />{flag}</li>)}</ul> : <Alert variant="success"><AlertTitle>Profile checks passed</AlertTitle><AlertDescription>No current quality warnings were detected.</AlertDescription></Alert>}</CardContent></Card></TabsContent>
      <TabsContent value="history"><Card><CardHeader><CardTitle>Change history</CardTitle></CardHeader><CardContent>{history.isPending ? <LoadingState title="Loading change history" /> : <ol className="space-y-3">{(history.data || []).map((entry: any) => <li key={entry.id} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black">{String(entry.action).replaceAll("_", " ")}</p><time className="text-xs text-muted-foreground">{new Date(entry.changed_at).toLocaleString()}</time></div><p className="mt-1 text-sm">{entry.field_name ? `${entry.field_name}: ${entry.old_value || "empty"} → ${entry.new_value || "empty"}` : "Student record event"}</p><p className="mt-1 text-xs text-muted-foreground">By {entry.changed_by} · {entry.source}</p></li>)}</ol>}</CardContent></Card></TabsContent>
    </Tabs><ProfileEditDialog id={id} profile={profile} open={editOpen} onOpenChange={setEditOpen} /><DeviceDialog id={id} open={deviceOpen} onOpenChange={setDeviceOpen} /><EnrollmentDialog studentId={id} current={activeEnrollment} open={enrollmentOpen} onOpenChange={setEnrollmentOpen} /><RetireDeviceDialog studentId={id} device={activeDevice} open={retireOpen} onOpenChange={setRetireOpen} /><EndEnrollmentDialog studentId={id} enrollment={activeEnrollment} open={endOpen} onOpenChange={setEndOpen} /><LegacyLinkDialog id={id} status={attendanceIdentity} open={legacyLinkOpen} onOpenChange={setLegacyLinkOpen} /></div>;
}
