import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ArrowLeft, Download } from "lucide-react";
import { downloadStaffExcel, fetchStaffAnalytics, fetchStaffPositions, updateStaffPosition, type StaffPosition } from "../api/staff";
import { useAuth } from "../context/AuthContext";
import { PageHeader } from "../components/common/page-header";
import { EmptyState, ErrorState, LoadingState } from "../components/common/state-message";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { NativeSelect } from "../components/ui/native-select";
import { getPageApiError } from "../lib/api/errors";
import { queryKeys } from "../lib/query/queryKeys";

const categories = ["LEADERSHIP", "TEACHING", "TEACHING_SUPPORT", "ADMINISTRATION", "FINANCE", "HR", "MARKETING", "IT", "FACILITIES", "SECURITY", "GENERAL_SUPPORT", "OTHER"];
function percent(value: number | null) { return value == null ? "Unavailable" : `${value.toFixed(1)}%`; }
function saveBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

function Distribution({ title, items }: { title: string; items: Array<{ label: string; count: number; percentage: number | null }> }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{!items.some((item) => item.count) ? <EmptyState title={`No ${title.toLowerCase()} data`} description="The source records do not contain a value for this dimension." /> : <div className="space-y-3"><table className="w-full text-sm"><caption className="sr-only">{title} distribution</caption><thead><tr><th scope="col" className="pb-2 text-left">Category</th><th scope="col" className="pb-2 text-right">Employees</th><th scope="col" className="pb-2 text-right">Share</th></tr></thead><tbody>{items.map((item) => <tr key={item.label} className="border-t border-border"><th scope="row" className="py-2 text-left font-semibold">{item.label}</th><td className="py-2 text-right tabular-nums">{item.count}</td><td className="py-2 pl-4 text-right"><div className="flex items-center justify-end gap-2"><span className="sr-only">{percent(item.percentage)}</span><div className="h-2 w-24 overflow-hidden rounded-full bg-surface-muted" aria-hidden="true"><div className="h-full rounded-full bg-brand" style={{ width: `${Math.max(0, Math.min(100, item.percentage ?? 0))}%` }} /></div><span aria-hidden="true">{percent(item.percentage)}</span></div></td></tr>)}</tbody></table></div>}</CardContent></Card>;
}

function PositionReview({ item, editable }: { item: StaffPosition; editable: boolean }) {
  const client = useQueryClient();
  const [title, setTitle] = useState(item.normalized_title);
  const [category, setCategory] = useState(item.position_category ?? "");
  const [teaching, setTeaching] = useState(item.is_teaching_role == null ? "" : String(item.is_teaching_role));
  const mutation = useMutation({ mutationFn: () => updateStaffPosition(item.id, { normalized_title: title.trim(), position_category: category || null, is_teaching_role: teaching === "" ? null : teaching === "true", status: "APPROVED" }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ["staff", "positions"] }), client.invalidateQueries({ queryKey: ["staff", "analytics"] })]); } });
  return <tr className="border-t border-border align-top"><th scope="row" className="px-3 py-3 text-left">{item.raw_title}<span className="block text-xs font-normal text-muted-foreground">{item.employee_count} employees · {item.status.toLowerCase()}</span></th><td className="px-3 py-3">{editable ? <Input aria-label={`Normalized title for ${item.raw_title}`} value={title} onChange={(event) => setTitle(event.target.value)} /> : item.normalized_title}</td><td className="px-3 py-3">{editable ? <NativeSelect aria-label={`Category for ${item.raw_title}`} value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Unclassified</option>{categories.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</NativeSelect> : category || "Unclassified"}</td><td className="px-3 py-3">{editable ? <NativeSelect aria-label={`Teaching role for ${item.raw_title}`} value={teaching} onChange={(event) => setTeaching(event.target.value)}><option value="">Not classified</option><option value="true">Teaching</option><option value="false">Non-teaching</option></NativeSelect> : teaching === "true" ? "Teaching" : teaching === "false" ? "Non-teaching" : "Not classified"}</td><td className="px-3 py-3">{editable && <Button size="sm" disabled={mutation.isPending || !title.trim() || category === "TEACHING" && teaching !== "true"} onClick={() => mutation.mutate()}>{mutation.isPending ? "Saving…" : "Save mapping"}</Button>}{mutation.error && <p role="alert" className="mt-1 text-xs text-rose-700">{getPageApiError(mutation.error, "Position mapping could not be saved.")}</p>}</td></tr>;
}

export default function StaffAnalytics() {
  const { can } = useAuth();
  const [asOfDate, setAsOfDate] = useState(new Date().toISOString().slice(0, 10));
  const [exporting, setExporting] = useState(false);
  const analytics = useQuery({ queryKey: queryKeys.staff.analytics({ as_of_date: asOfDate }), queryFn: () => fetchStaffAnalytics(asOfDate), enabled: can("view_staff_analytics") });
  const positions = useQuery({ queryKey: queryKeys.staff.positions("ALL"), queryFn: () => fetchStaffPositions("ALL"), enabled: can("view_staff_analytics") });
  const exportWorkbook = async () => { setExporting(true); try { saveBlob(await downloadStaffExcel({ status: "ALL" }), `employee-directory-${asOfDate}.xlsx`); } catch (error) { window.alert(getPageApiError(error, "Employee export could not be downloaded.")); } finally { setExporting(false); } };
  if (analytics.isPending) return <LoadingState title="Loading employee analytics" />;
  if (analytics.isError || !analytics.data) return <ErrorState title="Employee analytics unavailable" description={analytics.error?.message} />;
  const data = analytics.data;
  return <div className="space-y-6">
    <Link to="/staff" className="inline-flex items-center gap-2 text-sm font-bold text-brand hover:underline"><ArrowLeft className="size-4" />Back to Employees</Link>
    <PageHeader eyebrow="Employee management" title="Workforce analytics" description="Server-calculated employee, age, tenure, DAPODIK, NUPTK, and data-quality metrics." actions={can("export_staff") && <Button variant="outline" onClick={() => void exportWorkbook()} disabled={exporting}><Download className="size-4" />{exporting ? "Exporting…" : "Export workbook"}</Button>} />
    <div className="flex items-end gap-3"><div><Label htmlFor="staff-as-of">Reporting date</Label><Input id="staff-as-of" type="date" value={asOfDate} max={new Date().toISOString().slice(0, 10)} onChange={(event) => setAsOfDate(event.target.value)} /></div><span className="pb-2 text-sm text-muted-foreground">As of {data.as_of_date}</span></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
      {[["Active employees", data.workforce.active], ["Former employees", data.workforce.former], ["Teaching", data.workforce.teaching], ["Non-teaching", data.workforce.non_teaching], ["NUPTK coverage", percent(data.nuptk.coverage.percentage)], ["DAPODIK coverage", percent(data.dapodik.coverage.percentage)]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs font-black uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value ?? "Unavailable"}</p></CardContent></Card>)}
    </div>
    <div className="grid gap-4 xl:grid-cols-2"><Distribution title="Position headcount" items={data.positions} /><Distribution title="Age distribution" items={data.age.distribution} /><Distribution title="Tenure distribution" items={data.tenure.distribution} /><Distribution title="DAPODIK status" items={data.dapodik.distribution} /><Distribution title="Joining year" items={data.joining} /></div>
    <Card><CardHeader><CardTitle>Data quality</CardTitle><p className="text-sm text-muted-foreground">Completeness is the number of present values divided by eligible fields across all employees. It is not a weighted score.</p></CardHeader><CardContent><p className="mb-3 text-lg font-black">Overall field completeness: {percent(data.data_quality.fields.find((field) => field.field === "overall")?.coverage ?? null)}</p><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><caption className="sr-only">Employee data completeness by field</caption><thead><tr><th scope="col" className="py-2">Field</th><th scope="col" className="py-2 text-right">Present</th><th scope="col" className="py-2 text-right">Missing</th><th scope="col" className="py-2 text-right">Coverage</th></tr></thead><tbody>{data.data_quality.fields.map((field) => <tr key={field.field} className="border-t border-border"><th scope="row" className="py-2 text-left font-semibold">{field.field.replaceAll("_", " ")}</th><td className="py-2 text-right">{field.present}</td><td className="py-2 text-right">{field.missing}</td><td className="py-2 text-right">{percent(field.coverage)}</td></tr>)}</tbody></table></div><p className="mt-4 text-sm text-muted-foreground">Age coverage {data.age.coverage.count}/{data.workforce.total}; tenure coverage {data.tenure.coverage.count}/{data.workforce.total}; unclassified positions {data.data_quality.unmapped_position_count}.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Duplicate identity values", data.data_quality.duplicate_identity_count], ["Invalid identifiers", data.data_quality.invalid_identifier_count], ["Unmapped positions", data.data_quality.unmapped_position_count], ["Unresolved import conflicts", data.data_quality.unresolved_import_conflict_count]].map(([label, value]) => <div key={String(label)} className="rounded-md border border-border p-3"><p className="text-xs font-black uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle>Position title mappings</CardTitle><p className="text-sm text-muted-foreground">Source titles stay unchanged. Only approved mappings classify employees for analytics.</p></CardHeader><CardContent>{positions.isPending ? <LoadingState title="Loading position mappings" /> : positions.isError ? <ErrorState title="Position mappings unavailable" description={positions.error.message} /> : !positions.data?.length ? <EmptyState title="No position mappings" description="New source titles will appear here after they are imported or created." /> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><caption className="sr-only">Employee position mappings</caption><thead><tr className="text-left"><th scope="col" className="px-3 py-2">Source title</th><th scope="col" className="px-3 py-2">Normalized title</th><th scope="col" className="px-3 py-2">Category</th><th scope="col" className="px-3 py-2">Teaching role</th><th scope="col" className="px-3 py-2">Action</th></tr></thead><tbody>{positions.data.map((item) => <PositionReview key={item.id} item={item} editable={can("manage_staff")} />)}</tbody></table></div>}</CardContent></Card>
  </div>;
}
